### ISSUE TITLE
AA3 help

### ISSUE THREAD

**Issue by Schteven** [Austinb/GameQ#100]
Hi

Is it possible with GameQ to get a full list of players on the requested server including there playerstats (score, kills, kia, roe, etc.)

It only shows the score and time of a player for this game.

Greetings

**Comment by firefly2442** [comment]
Assuming you're asking about America's Army 3.

http://aa3.americasarmy.com/

**Comment by Austinb** [comment]
The short answer is no, unfortunately. 

Since AA3 v3.2 came out it has been using the A2S protocol, also known as Source.  Same protocol used by games like CS:S, TF2, etc..  The only information provided is the following: Name, Score & Duration

The Source protocol is extremely limited in its player response when compared to some other protocols.  I believe this is by design.  More info can be found at https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_4 if you are curious.
