### ISSUE TITLE
world of warcraft

### ISSUE THREAD

**Issue by Darklordd** [Austinb/GameQ#103]
Hi, is it possible to add world of warcraft to GameQ? Now I use fsockopen

**Comment by Austinb** [comment]
What information would you want to get?  I am not sure any traditional protocol exists to get information such as number of players, server name, etc.. There is an api that can be used to get information such as realm status such as http://us.battle.net/api/wow/realm/status or http://us.battle.net/api/wow/realm/status?realm=name but I am not sure how beneficial this information is since WoW servers are operated by Blizzard.

**Comment by Darklordd** [comment]
I need realm status, number of players, there are many pirate servers of wow based on trinitycore http://www.trinitycore.org/ or other frameworks

**Comment by Austinb** [comment]
Is there any information on how to ping these pirate servers?  I can make a class to call the API for the real WoW servers but they do not give a numeric player count.  It appears to be one of low, medium, high, etc... Best I can find is something like http://us.battle.net/api/wow/realm/status?realms=Blackrock but I do not have a lot of time to go hunting around API docs and what not.

Any other insights you can provide would be helpful.  Thanks.

**Comment by Darklordd** [comment]
Thanks for the answer. I think this http://us.battle.net/api/wow/realm/status?realms=Blackrock is that what I need, because player count we can get only from server database http://collab.kpsn.org/display/tc/DB_Auth_realmlist field population.
Here is some api docs http://blizzard.github.io/api-wow-docs/

**Comment by Darklordd** [comment]
also some links from wow forum http://us.battle.net/wow/en/forum/2626217/

**Comment by Darklordd** [comment]
If I understand correctly, we can get player count like percentage (low, medium, high), wintergrasp and tolbarad statuses, name and type of realm. That's enough for monitoring.
