### ISSUE TITLE
Custom list Undefined index Error

### ISSUE THREAD

**Issue by Bestrafung** [Austinb/GameQ#114]
I'm trying to make a custom script that shows only the hostname, map, current players, max players, and if possible the IP:port. I started with the "quick and dirty" example and tried to modify it from there. I thought changing it from: print_r($results); to: print_r($results['hostname']); would work to output the hostname. Instead all I get is the following error: Notice: Undefined index: hostname

Here's the full code that I have at the moment, I'd really appreciate it if anyone could tell me what I'm doing wrong. My PHP skills are extremely lacking and I can't figure what's wrong. If I change it back to print_r($results); it works fine.

<?
error_reporting(E_ALL);
require 'gameq.php';
$game = $_GET["game"];
$ip = $_GET["ip"];
$port = $_GET["port"];

$gq = new GameQ();
$gq->addServer(array(
    'id' => 'my_server',
    'type' => $game,
    'host' => $ip . ":" . $port,
));
$results = $gq->requestData();
echo "<pre>";
print_r($results['hostname']);
echo "</pre>";
?>

**Comment by Bestrafung** [comment]
I just returned to this and noticed that the code in my previous post didn't show correctly. The echo lines are supposed to be opening and closing pre tags. Anyway, does anyone have an idea what I'm doing wrong or where I can learn some more? I've been trying to read and follow the PHP manual concerning print and print_r and arrays in general but it's still beyond me. I had this working once on the old GameQ but lost the code due to a corrupted backup. I still have no idea how I had this working before, I was sure the print_r($results['hostname']); was how I did it. Do I need to try to set something similar to the below instead? I'm going to try it when I get the chance but I'm sure it's not right.

$hostname = $gq->requestData(hostname);

<p>Hostname: <?php echo "$hostname"; ?></p>

**Comment by Austinb** [comment]
the requestData() method does not have any arguments.  All it does is go and do the work to gather all of the information. There are no real shortcuts to the data entries in the array returned by that method.

Using print_r is a good place to start since it will show you the structure of the array and where all the data is located.  If you are having trouble seeing the output from print_r in a browser try adding `echo '<pre>';` before the print_r output. This will make the browser format the output so it is more readable.
