### ISSUE TITLE
Version 3 Requests

### ISSUE THREAD

**Issue by Austinb** [Austinb/GameQ#170]
I have begun the planning stages of version 3 of this project.  The main idea is to make the core simpler and faster with emphasis on using new abilities and functions provided in PHP 5.3 and 5.4 (i.e. namespaces, traits, anonymous functions).  I want to also make it easier for other people to contribute to the project since my time has become limited.

Planned changes:
- [x] Make querying simpler and more stable. Should be able to query any number of servers (within reason) and return a response from all. Split off querying dirty work to its own class/library.
- [x] Change the server addition syntax to use the client port as the port passed. For known differences between client and query ports calculate the query port and use that automatically.  For servers that allow specific differences between client and query ports (i.e server config settings) allow an option flag to pass the query port, it will have to be known before hand in this case. But this is also the case with v2, you must know the server query port in advance.
- [x] Build tests with valid raw query responses to validate protocols.
- [x] Rebuild filters to be simpler and cleaner.
- [x] Add normalize to every protocol class. 
- [x] Load lists of servers using a JSON formatted file.

Optional changes:
- Add in caching layer with defaults for file, memcached & redis. Must be easily extendable to allow other/future options. 
- Allow queries to recover from failed response/empty response x number of times.

I will continue to support v2 as much as I can but it is becoming harder to fix issues especially with older games.  Adding testing as we go will allow easier diagnosis especially for games that break protocol standards.

Please provide thoughts and other ideas you would like incorporated into the new version.  I will update this list to reflect changes.  I am trying to minimize the number of extensions/addons required to operate the library. That being said if there is a better way to do something (i.e. using sockets instead of native php streams) I am ok with adding a library in as an option.

**Comment by KostyaEsmukov** [comment]
Lets think about typical usage of the gamequery software. The most common purpose is to show gameserver status on the webpage. Webpages could be queried rapidly, so status caching must be implemented. Some easy instructions about how to setup this by yourself would be very helpful for newbies. But this is not something that should be included in library. Just an example code or some kind of plugin that implements this idea (using MySQL as the most common persistent storage for PHP users).

As game servers might response slow, but webpages should load fast, querying shouldn't be done during page loading. So querying should be done by some daemon in background. That mens that library should be daemon-oriented.

Though I think Python is better suited for daemons (multithreading, more stable, cleaner syntax, consumes less resources, etc), PHP is more familiar for people who would ever need to query gameservers. But Python should be better anyway.

Regarding architecture I've got some thoughts:
- Isn't it better(faster) to reuse sockets, instead of creating them before every query, when querying in daemon
- Teamspeak 3 bans if query too often. This is something that should be mentioned in protocols.
- Try to make protocols very simple, even if it will lead to a more complicated core. Protocols will be changed more often than core.

**Comment by rststeam** [comment]
I would just like to say that you keep in mind that GamePanelX and some other Game Panels use this query to get server status. It's not only used for websites. So in V3 it should be for both as it is now. The faster and less complicated code is better. Keep it up austin !!! .  I can support by testing if needed

**Comment by Austinb** [comment]
Notes about the comments above:
I added a caching requirment in the simplest form with some out of the box defaults. Will require a bit of thought to bring it into the run time options.

For sockets I am currently working on reworking them with the native functions (streams) to be smarter.  Reusing sockets is a good idea and actually should get rid of the 2 different methods of querying that exist in v2 due to GameSpy 3 having to be on the same socket as the auth request. Also building them so another method can be dropped in easier.  Still hashing that part out.

That being said there is an issue when sending multiple packets to the same socket because you have to read then write in sequence or it is hard to distinguish what response for which packet you are getting back, think of Source where there is one packet for info, one for players, etc...  One of the speed ups in v2 was being able to open up a socket for each packet and read back the responses.  This allows for more data to be sent and received at once and speed things up.  This does not work for GameSpy 3 though.  I think all of the GameSpy3/4 games only send one packet for all of the server's information. So that will fit into the one socket for one packet layout that I am toying with currently.  And since I will be reusing the authenticate socket to send out queries it should work.  

As far as simplifying the protocols I have removed all of the sever specific information such as ip, port, etc.. from the protocols core and moved them to a new server class to be used as a go between. Most of them only have names and default ports. Default ports will probably be removed in v3, no real use for them it seems. Most of the dirty work is done by the base protocol class that individual classes extend. What other suggestions do you have for simplifying the actual protocol classes?  Moving forward I will probably stick to the one class per game setup since it allows for the most flexibility when games built on a protocol dont follow its standards exactly. Like ARMA 2: OA and a few others. Its also simple to add in new games if they follow the protocol standard.  Or you can use the base class in most cases.

**Comment by Austinb** [comment]
Now that I think about it I will look and see how possible it is to condense all of the requests into one socket per server.  It may be possible to dump all of the requests one after another then read them all back out on a non-blocking socket.  So long as the response has a unique header, source and some others do. I will do some experimenting and see what happens.

**Comment by KostyaEsmukov** [comment]
Well i've (successfully) tried to work around these 'sockets things' in my GameQ3 library using the way you're thinking about. It works pretty good, but my code is huge and is hard to maintain by other developers. If you feel to go this way, find a time to see my implementation. You may find many caveats and workaround them during architecture thinking.

I'm using my library as a daemon and i've found out that PHP is really bad for this, so I would greatly support Python version of GameQ. Python is really better suited for this kind of tasks. Results will be still accessible in PHP sites (generally any dynamic sites) via some kind of persistent storage. Final solution will be much better and common for everyone.

Regarding default ports. It depends on the usage. Default ports are needed for people who add servers manually. I mean large server list sites like a gametracker. This requires less information from user, because many gameservers are working on their default port. So just keeping the list of default ports would be enough for such sites.

About protocols simplifying. All things like which way to process packets, challenge packets should be in protocols. In GameQ v2 challenge packets are requested by the will of the core. But what if there will be some special case, which is not covered by the way it works in v2? Again, see my protocols as an example of what am I trying to say.

**Comment by Austinb** [comment]
First functional version of the v3 branch has been pushed up.  This only works for source. It should be fit for any source based game. Changes include going to a 1 socket per server and sending all necessary packets via the one socket.  I did notice some response issues in that certain responses were being dropped.  Filtering and all of the other addons are missing at this point.  I want to get the base good and working properly before moving toward filtering. 

The base setup for the new library is more or less set but is still up for changing if someone has better ideas on how to lay out everything.  I split apart the server, query and protocol sections into their own classes to allow for easier maintenance as well as simplify things by separation. Each also include their own exception classes to make catching the source of problems easier. 

I will probably make some tweaks to the old results and buffer libraries later but for now they are the same as v2 just with namespaces. 

Please test as much as you can and provide feedback.  I will try to schedule some more dev time in the coming weeks but I will need some real world testing to see if this new query calling will work well.   Also want to see what other bugs are found since this is the most important part.

**Comment by firefly2442** [comment]
What do you think about adding support for XML output?  This would then allow external applications to use this data.

**Comment by hammermaps** [comment]
Use json_encode with Option JSON_FORCE_OBJECT

**Comment by Blackskyliner** [comment]
First and foremost we should think about an easy to use interface.
Lets prototype some easy example and then implement against that. 

(The new v3 seems just as odd in some cases as the v2 before...)
The current one is a bit... Oldschool...

---

XML Output? Meh... why not just use JSON? In this case it does the job as well as XML but is far more readable. And you'll save the other developers the hassle of biting through XML proccessing in PHP (which is and was never beatiful, as far as I'm concerned)

---

Will you break the current API? If so then break it with some better interface, as stated in the 1 paragraph think about an easy usage. Then try to implement this usage. The Zen of TestDriven Development (TDD) may be no bad choice here. It will also result in more testable code, as you write the tests first ;)

---

If I only had some time to tinker... But I am working on my Bachelor Thesis atm. so I don't have time to work on OpenSource projects...

I also know that I'm a bit late on this issue (as some v3 prototype already exists) but a frind of mine which helps me in my community projects and is coding some stuff atm. - like a new serverviewer ;) - pointed out that you do some rework, so I'd thought about giving my five cents here :)

---

EDIT1:
Oh I almost forgot: Do the requirements checking, like BZip, in the constructor of the Protocol not in the depths of parsing...

**Comment by Austinb** [comment]
I am open to any input on how servers should be added, what filters and how they should be applied would be welcome and the like.  I had just worked on the bones of the actual querying side since this is more difficult to test without a set of servers.  Adding a dummy server launcher that just spits back proper responses would be another option.  Changing how the servers are added (addServer) is fairly easy if there is simpler or more programmatic way to do it. Same with the response outputs if they need to be changed or if other methods are wanted.  Though things like XML will require more dependencies to be installed for PHP in some cases either complied, extension or pear. 

For dependencies the reason A2S Bzip2 is so late is because it is only required if you use source and even then it is only needed for the rules query for some specific games.  It would be easy to move it to the beginning but some users may have no need for the dependency and worse yet no way to actually install it. 

I havent had a lot of time to devote to this but any input for any aspect would be welcome.  Also if anyone has a ton of servers online they can test with the v3 source protocol please do and let me know how the system fairs.  Want to fix any querying bottlenecks in v3 as much as possible.

**Comment by Austinb** [comment]
Version 3 is to the point now where it needs to be tested to see how the changes made affect its speed and scalibity.  Please use the @dev tag when pulling down for composer if you wish to test.

One of the biggest changes is how servers are added and how GameQ is invoked. Please see the [examples](https://github.com/Austinb/GameQ/wiki/Examples%20v3) page for some help on this front. Biggest change is now all servers require the client port to be defined for the _host_ key.  For servers with custom query ports [see this](https://github.com/Austinb/GameQ/wiki/Examples-v3#different-client-and-query-ports).  Also normalize is added by default to the filtering so there is no need to add this anymore.  Most of the protocol classes have been paired down as much as possible but if you see room for improvement let us know. 

Also any feedback on how the testing is laid out or accomplished would be appreciated.  I am still new to the testing side of things but it has already paid off while developing version 3. Moving forward protocols will not be added that can not be tested directly using real responses from servers (See Soldat).  These are saved in flat files so no actual querying is done to live servers when tests are run. 

Missing items:
- Not all servers from v2 have been ported.  See [supported list](https://github.com/Austinb/GameQ/wiki/Supported-servers-list-v3) for a current list.
- Soldat servers needed to gather tests from
- Caching layer - Will try to add before RC state

**Comment by skylord123** [comment]
I will try and see if I can do some benchmarks between the versions. I don't know when I will be able to. I will probably run this against a couple thousand servers.

I just thought I should let you know of a composer issue I have come accross using `"austinb/gameq": "3.*@stable"`:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package austinb/gameq 3.* could not be found.
  Problem 2
    - Installation request for symfony/framework-standard-edition 2.3.x-dev -> satisfiable by symfony/framework-standard-edition[2.3.x-dev].
    - symfony/framework-standard-edition 2.3.x-dev requires austinb/gameq 3.* -> no matching package found.
```

I'm guesing this is because v3 is still in alpha tesitng and I will just use `3.x-dev` for now. Let me know if I should use a different version. This is just the latest branch updated according to packagist https://packagist.org/packages/austinb/gameq

@Austinb I will try and contribute some work in the next week or two.

**Comment by flowdee** [comment]
any expectations when v3 will be released or the beta at least production ready?

**Comment by Austinb** [comment]
@skylord123 @dev is fine as that is where the latest version is anyway. 

@flowdee it should be stable enough for use in a production environment but is lacking in many of the protocols that v2 has.  So if you need any of those you will have to continue to use v2.  I haven't had a lot of time lately to work on this.  Hopefully will get back to it.

**Comment by flowdee** [comment]
@Austinb thanks for your reply! fine for me then :)

**Comment by muuvmuuv** [comment]
Are there new results or a expection when its released ?

**Comment by Verox-** [comment]
@muuvmuuv You can download v3 from https://github.com/Austinb/GameQ/tree/v3 but mind, it is still in development.

**Comment by Austinb** [comment]
Need more testing and feedback on how it operates in the real world.  I do not have access to large blocks of servers.  My main concerns are the speed and reliability with large server lists.

**Comment by skylord123** [comment]
@Austinb Sorry about not getting back to this thread. Been very busy. I am in the middle of a move right now.

I built an application which is like gametracker for tracking servers. I will do some testing on big server lists in a week or two and compare it to the old version of gametracker.

Will it take much time to change the code I have to work with the new version?

**Comment by Austinb** [comment]
Closing this old issue thread.  If there are issues specific to GameQ v3 (not for the protocols it supports) please open up a new issue.
