### ISSUE TITLE
Install Gameq

### ISSUE THREAD

**Issue by Hronici** [Austinb/GameQ#171]
Hello! I can not install GameQ on site. Even standard protocols will generate an error. see screenshot http://storage8.static.itmages.ru/i/14/0309/h_1394388990_4666663_dab117610d.png

If you do like this  http://storage8.static.itmages.ru/i/14/0309/h_1394389349_8018662_bbe1baecda.png
that errors go, but nothing.

What am I doing wrong? How do I display the status of the server and at least some data?

Sorry for my english

**Comment by Austinb** [comment]
What you are using looks like v1 syntax.  The syntax changed for adding servers in v2 to allow for easier options.  Have a look at https://github.com/Austinb/GameQ/wiki/Usage-%26-Examples-v2 for some examples.

If you are trying to use v1 I am not really providing any support for it due to its age. There may be other people on here with some help for v1.
