### ISSUE TITLE
php 5.3 and gameq

### ISSUE THREAD

**Issue by giovannimatina** [Austinb/GameQ#2]
Hi, i'm using the latest version of gameq, but it's running on php 5.3, some time ago in another hosting (with php 5.2) it work perfectly, but now my new hosting have only php 5.3 and some functions, as stream_socket_client(), and other updated with 5.3, sometimes give this error: PHP Warning:  stream_socket_client(): failed to bind to '0:10002', system said: Address already in use in /home/*****/Austinb-GameQ/GameQ/Communicate.php on line 119. There are any updates for solve this problem? What you think?

**Comment by Austinb** [comment]
Which version are you using?

The issue is part of the socket system binding for responses.  The way the code works, I did not write this part, is that each server and its query calls are sent out all at once and the sockets are bound to ports locally to recieve the response from the queried servers.  The issue is that the there is no logic in v1 of GameQ (nor is there any in v2 at this time) to check and make sure that the socket can be bound.

I will see if I can update the v1 code without too much work.  I will add, if possible, some checks in the v2 to be smarter when binding for responses.

Check on and add available port check.  Dont blindly try to attach to ports, check first.

**Comment by Austinb** [comment]
To update I was wrong about what the context was used for.  It is actually to specify the outbound ip:port for connections. Removing it should just make the system pick available outbound ports on its own.  Seems to work fine in v2.

The actual issue with the warning is probably a change from PHP 5.2 to 5.3 though I am unable to find a change log entry.
