### ISSUE TITLE
rename classes from GameQ to GameQ2

### ISSUE THREAD

**Issue by gcphost** [Austinb/GameQ#20]
Since GameQ V2 does not yet have all the support of GameQ1 is there any way you can rename your classes to GameQ2 so we can use both v1 and v2? 

Currently its not possible to use both v1 and v2 in the same script (looping over and over) - it causes issues.

If you renamed the classes we could use both versions at the same time and would help a lot.

thanks!

**Comment by Austinb** [comment]
Changing the v2 to GameQ2 would require changing every class and sub-folder.  Don't really want to rename them all since v2 was written to replace v1.  Unless there are a lot of users out there that want the class name changed I am leaning towards not changing it at this time. 

Feel free to test out the name change and see if it will work.  My guess is you will have problems running both together since they more or less use the same namespace. Please report back any results.

**Comment by Austinb** [comment]
Also, if there are any games that are not supported that v1 does support (and servers are still available) please feel free to open up support requests for each game.  Any of the newer games missing I just have not gotten around to them as I have not played the game(s).
