### ISSUE TITLE
DayZ Mod protocol changes

### ISSUE THREAD

**Issue by iamguyfawkes** [Austinb/GameQ#202]
DayZ Mod script doesn't work. As I know, protocol changed from gamespy to source...

But, changing the line to `class GameQ_Protocols_Dayzmod extends GameQ_Protocols_Source` doesn't solve the problem.

What should I do to fix this?

**Comment by Austinb** [comment]
Please provide a pull request and I can merge it in.  Sorry for the long delay.

**Comment by Austinb** [comment]
Default query port for this game seems to be 27016 not 2303 fyi.

**Comment by Verox-** [comment]
Commit ea05cd0 is not correct and should be reverted. Arma 2 was never changed to the Source query protocol, Operation Arrowhead was (I fixed this in pr #190 a few months ago.) 
Additionally, DayZ cannot run on base Arma 2 (without Operation Arrowhead) so it doesn't really apply to this issue.

**Comment by Austinb** [comment]
Actually arma 2 was changed to use source which is where the 27016 port comment came from.  I tested using many different servers from gametracker.com. I tested one known working dayz mod with a known query port and it appears to be working. 46.4.53.163:2301

Please test and send me any known ip:query_port combos that are not working.

**Comment by Verox-** [comment]
DayZ mod can only physically run on Arma 2 Operation Arrowhead servers. Operation Arrowhead is a standalone expansion for Arma 2 which replaces a lot of game code, as a result DayZ doesn't actually work on base Arma 2 servers without major modification. The servers you are testing are running Operation Arrowhead and will respond to A2S protocol as it was switched over a few months ago; Arma2, however, was never switched over and all support for it has ended.

If you look under Server Variables on Gametracker you can see it's running OA.

**Comment by Austinb** [comment]
I was unaware of the internal difference since it seems OA is referenced as arma2 in most places.  If not and there is no more support for vanilla arma2 then it's support should be removed right? Are there any vanilla arma2 servers running anywhere? I checked a link I found http://master.bistudio.com/?page=1&count=10&filter%5Bstatus%5D=1&game_id=1 but there are no servers listed.

**Comment by Austinb** [comment]
Never mind on it not showing any servers, it appears it doesn't work in chrome for some reason on my windows machine.

**Comment by Verox-** [comment]
They won't report to any master server anymore since Gamespy went down, I can only imagine certain private servers would still be online, however, if they were online (or come online in the future) then the query protocol will be the only way they can get information about their servers. Libraries like this could potentially be of use in those cases.
The Gamespyv3 query should still work, there's no reason to remove capability that might be of use to someone.
