### ISSUE TITLE
CSGO player name issue

### ISSUE THREAD

**Issue by Brophy** [Austinb/GameQ#204]
Hello,

When trying to get the playerlist from a CSGO server, every playername in the array is "Max Players", here is the array which is being returned.

[players] => Array
        (
            [0] => Array
                (
                    [id] => 0
                    [name] => Max Players
                    [score] => 10
                    [time] => 3479.83984375
                    [gq_name] => Max Players
                    [gq_kills] => 
                    [gq_deaths] => 
                    [gq_score] => 10
                    [gq_ping] => 
                )

```
    )
```

**Comment by Kandru** [comment]
Could you please send me a example server IP + Port that you used?

**Comment by Brophy** [comment]
46.105.108.9:27025

**Comment by Kandru** [comment]
Do you have mods on your server? Or is this a vanilla server? I tried a few other servers (94.249.140.42:27015 , 62.113.205.25:27015 , 5.175.245.41:27015) and they work fine. Even the steam ingame browser shows my name on your server as "Max Players". So the issue is NOT related to GameQ.

See attached screenshot.

![csgo 2014-12-15 09-04-53-04](https://cloud.githubusercontent.com/assets/1965552/5432293/9bcc7718-8439-11e4-8228-943a6e35520e.png)

**Comment by Brophy** [comment]
Apologies, I have found out you need to set the following in your server.cfg to enable the output:

host_name_store 1
host_info_show 2
host_players_show 2
