### ISSUE TITLE
armedassault3 protocol does not fully expose returned information.

### ISSUE THREAD

**Issue by Verox-** [Austinb/GameQ#212]
Arma 3 has a somewhat bizzare method of returning extra information about the server. A string is returned which could either be parsed in GameQ it's self or just given as is and allow the user to do what they want with it.
Currently GameQ seems to discard this information.

Example, extra information is bolded.
\ff\ff\ff\ffI\11UnitedOperations.Net - SRV1 - ACRE2\00Altis\00Arma3\00CO36 - ZEUS - Platoon V12e\00\00\00\19&\00dw\01\001.36.128579\00\b1b\t\05\e4s\dd\c5\13@\01 **bt,r136,n0,s7,i1,mf,lf,vt,dt,tzcoop,g65545,c-79-42,pw,** \00\92\a3\01\00\00\00\00\00

Documentation:
https://community.bistudio.com/wiki/STEAMWORKSquery

**Comment by Austinb** [comment]
Is this a response using "Server Details" query?  If you look at the source to parse this response the function steps through the response grabbing specified information based on the A2S protocol specifications.   Given that link you posted it appears that steamworks has taken the place of GameSpy as the protocol but is not an exact clone of the A2S protocol in terms of its responses.  Is this correct?  if so it would probably be best to implement a new extension of the source protocol class and process the different response(s) there since the packets being sent are the same as a "normal" source server. 

I have been on other projects in recent months and have not kept up with online gaming much during that time.

**Comment by Verox-** [comment]
Yeah the string is returned with an A2S_INFO query, a lot of the information you want to know about a server is inside the string, too.
They did replace GameSpy with A2S but for some bizarre reason they decided to try and mimic the GameSpy return inside the A2S protocol instead of using the protocol as intended.

I agree it would be best to implement a new extension and work from there.

**Comment by Austinb** [comment]
Is there any other information for this query?  Building the new details parser but there is some data after the current version (which is a string now) and where bt, starts which is the beginning of SetGameTags table. 

In your example it would be the section \b1b\t\05\e4s\dd\c5\13@\01

Also there is trailing information after pw, which I have no idea what it is for either.

**Comment by Austinb** [comment]
Actually Steamworks is using the EDF (extra data flag) from the A2S spec.  That makes sense now.
