### ISSUE TITLE
Arma 2/3 - Mod Variable Name

### ISSUE THREAD

**Issue by firefly2442** [Austinb/GameQ#246]
In Arma 2/3, it appears there are different responses regarding which mods are running.  In GameQ v2, I believe this was consolidated to a single variable called `gq_mods`.  For GameQ v3, I think it's using just the straight value sent by the server (this is based on looking at the tests JSON data).

The trouble is, the names are different.
- Arma 3: `sigNames:0-1`
- Arma 2 OA: `sigNames:0-2`

It's also not a very "user friendly" variable name.  Do you think this is something that could be changed in the query process or are you trying to keep the data "as-is"?

**Comment by Austinb** [comment]
Both games are based on Source which provides the keywords for these values.  It may be possible to add a gq_mod for normalize if that is what you are looking for.

**Comment by Verox-** [comment]
The names used to be like that because of a character limit in the Gamespyv3 protocol (the protocol A2:OA used to use), so they'd fill sigNames:0-1 up and then, if the modline was long enough, progress on to sigNames:0-2 then sigNames:0-3 ect ect.

It'd be nice to have it normalized but the raw data should always be available in my opinion.

**Comment by Austinb** [comment]
I believe those responses are part of the "rules" query which the class is provided the name of the key and its value.  These are defined by the server itself.  That being said it could be possible to combine these split values into one for those specific games if there is information available on how it should be reconstructed.  Is there anything like that available?
