### ISSUE TITLE
TeamSpeak 3 - server down

### ISSUE THREAD

**Issue by AmkCity** [Austinb/GameQ#28]
When add the two servers TimSpik 3, at 20 second data request, the server hangs after a short interval of time

**Comment by Feertti** [comment]
I think that you face a problem with TS flood protection.
"Per default, the TeamSpeak 3 Server will not allow more than 10 commands within 3 seconds from the same source."
Check whitelist from this manual http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

**Comment by Austinb** [comment]
Sorry for the delayed response.

Feertti might be correct.  Best practice is to limit the number of queries you send to any server.  If you have the GameQ script called upon page load you need to put a caching layer in between the call from the page and GameQ.  Make the GameQ call only when the cache expires otherwise read the information from cache (memcache, file, etc...).

For most cases an update every couple of minutes or greater is probably sufficient.

Please let me know if you are having a specific issue with the call itself even when using caching or limiting your calls to the server.

**Comment by AmkCity** [comment]
My server crashes when I query the status of the other server teamspeak

**Comment by Austinb** [comment]
Can you pm me the ip and query port of the server so I can look?  Also what version of the server are you running?

**Comment by AmkCity** [comment]
Unfortunately, these servers are located within a large local network and do not have access to the internet

**Comment by Austinb** [comment]
What version of the server are you running?  Perhaps there was a change in how it operates in 3.0.5. Do you have any external servers that show the same behavior?

**Comment by Austinb** [comment]
If you have any other information about this issue?  If so please reopen it.
