### ISSUE TITLE
Querying Mumble makes it crash

### ISSUE THREAD

**Issue by kraxarn** [Austinb/GameQ#298]
Querying a Mumble server makes it crash
`Warning: stream_socket_client(): unable to connect to tcp://213.89.41.193:-9138 (Connection refused)`

`Fatal error: Uncaught GameQ\Exception\Query: GameQ\Query\Native::create Error creating socket to server 213.89.41.193:-9138. Error: Connection refused`

**Comment by Austinb** [comment]
Pull down latest version (3.0.4) and let me know if the issue persists.  This should be fixed in #293.

**Comment by Austinb** [comment]
Use latest @dev and verify it fixes your issue.

**Comment by kraxarn** [comment]
No longer crashes, but returns query with empty data. Is the GT Murmur plugin required?

**Comment by Austinb** [comment]
The default response is a base response with a lot missing content.  This happens if the server does not respond, is offline or the wrong ip:port information was provided.  You can test with debug mode set to true and see if there any exceptions thrown and report those back to me.  Otherwise I would check the server itself.

**Comment by Austinb** [comment]
If you are still having issues please reopen this issue.

**Comment by kraxarn** [comment]
Sorry, haven't looked much into it, but the crash is fixed and it's probably something with the server. Thanks anyway.
