### ISSUE TITLE
[] operator not supported for strings error

### ISSUE THREAD

**Issue by chaot1x** [Austinb/GameQ#307]
In v3 sometimes it throws this error

```
[2016-03-25 19:42:15] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: [] operator not supported for strings in \site\vendor\austinb\gameq\src\GameQ\Protocols\Source.php:185
```

Any ideas how to fix?

**Comment by Austinb** [comment]
What release of 3?  Also what version of PHP?  Can you provide instances when this issue occurs such as specific servers?

A first glance it maybe the result of $packet_id being empty causing it to try to initialize two arrays. But that doesn't explain the string error.  The variables are defined as arrays so that doesn't make sense right now.  

Do you have a more detailed exception trace you can provide?

**Comment by chaot1x** [comment]
I don't know which subversion, but I updated it few days ago. PHP 7.0.3. Servers are random cs:go servers. 

Full stack trace here - https://gist.github.com/chaotixlv/7c97c0e77246916a0ebd but its kinda useless anyway, because 99% of it contains laravel stuff
Code im using to retrieve information - https://gist.github.com/chaotixlv/1b9896ba6f6c076fb3a3

And servers array contains basic stuff / id - type - host - and one custom (addr) /

**Comment by Austinb** [comment]
The issue is in the section of the source protocol where it is checking for split packets and organizing them so they can be reassembled. If you can give me some servers where the issue occurred I may be able to narrow down the cause.  It could be response from the specific server possibly due to a mod the server is running.

**Comment by chaot1x** [comment]
Both server hosts:
46.174.50.198:27015 - I don't remember mod for this server (picked first from gametracker)
195.60.249.35:27015 - This one is casual i think

**Comment by Austinb** [comment]
What game types are these servers?

**Comment by Austinb** [comment]
I tested both.  The first one has a hostname and some other fields with non-ascii characters that could be messing things up if there is an incomplete packet or something but I was unable to recreate the error.  If you can provide more info as to when it happens and the output let me know.

For the second server it was empty.  The hostname looked ok and did not see any other non-ascii characters in the response.

**Comment by chaot1x** [comment]
@Austinb It happens very rarely, I checked logs since I started to use GameQ in my project (January) only 4 times this error showed up.

**Comment by Austinb** [comment]
If this becomes a more pronounced issue please reopen this ticket or create a new one and reference this one.

**Comment by vimishor** [comment]
@Austinb I did some testing with version 3.0.9 and after querying some servers in a loop (_I was forced to do this because this issue occurs very rare_), I managed to save a [capture](https://github.com/Austinb/GameQ/files/654801/gameq_capture_issue-307.txt.gz) when this issue occured.

Using the data from this file, I tried to parse it:

``` php
<?php

require __DIR__.'/vendor/autoload.php';

use GameQ\Buffer;
use GameQ\Protocols\Source;

$filename   = "gameq_capture_issue-307.txt";
$data       = str_replace("\n", "", file_get_contents($filename));
$protocol   = new Source();

$protocol->packetResponse(explode('||', $data));

var_dump($protocol->processResponse());

```

Which ended with the previuos mentioned fatal error: "[] operator not supported for strings".

My quick fix was to check if array is initialized after reading [the packet id](https://github.com/Austinb/GameQ/blob/v3.0.9/src/GameQ/Protocols/Source.php#L182) and initialize it if needed:

``` php
if (!is_array($packets[$packet_id])) {
    $packets[$packet_id] = array();
}
```

If you consider this a proper fix, give me a ping and I can send a PR.

**Comment by Austinb** [comment]
@vimishor Make sure you re-open issues if you are providing more information. Can you send me the capture file for this? Also what version of PHP are you seeing this issue? I am curious if this is a specific issue with a version of php because you should be able to short initialize an array like it is written now.  But that doesn't mean it is the correct way.

**Comment by Austinb** [comment]
@vimishor Nevermind on the capture file I just saw it was linked in your response.  I will take a look at it.

I still would like all the server information you can give me such as PHP version so I can test directly to try to replicate the issue.

**Comment by vimishor** [comment]
> @vimishor Make sure you re-open issues if you are providing more information.

I can't do that because I'm not the original submitter of this issue, so I don't have enough privileges.

> I still would like all the server information you can give me such as PHP version so I can test directly to try to replicate the issue.

I think that this issue is more related to the payload rather then the environment. I tested the code sample from my previous comment with provided [capture](https://github.com/Austinb/GameQ/files/654801/gameq_capture_issue-307.txt.gz) file on PHP `5.4.45`, `5.5.24`, `5.6.0` and `7.0.12`. It failed on all versions.

I had some time and looked at the code from [Source::processResponse](https://github.com/Austinb/GameQ/blob/v3.0.9/src/GameQ/Protocols/Source.php#L163-L187) method and provided capture file.

When we loop over each `packets_response`, after 2 itterations, the `$packets` variable will look something like this:

``` php
array(2) {
  [0]=>
  string(266) "I[TR] Burak Oyunda Fun Sunucusu #Sunucuadresi.comsurf_ski_2_GOcsgoSunucuadresi Hosties/Jailbreak�6dl1.35.6.2��i��
                 0!kni,!sunucuadresi,awp,cs,csgo,dr,fun,isyan !ws,isyancı,isyancılar,jail,jailbreak,jb,mg,public,surf,tr,turk,turkish,zm,zombie�"
  [1]=>
  string(42) "D�A�
                     �@�f�@1x�@"
}
```

At the 3rd iteration, the `$header` will be equal to `-2` (_so the `else` part of the block will be executed_) and here comes the issue: `$packet_id` will be equal to `1`.

That means that at [line 185](https://github.com/Austinb/GameQ/blob/v3.0.9/src/GameQ/Protocols/Source.php#L185) we will try to add a new element on a string (_i.e: $packets[1] which already exists and is of type string_) which terminates with an error.

**Comment by Austinb** [comment]
So I had some time to spend on this and your capture helped immensely trying to figure out what was going on.  

In that capture you sent the first two responses are normal, non-split packets.  So as part of the looping when the packets first come back if they are not split the packets are just shoved into an number indexed array (normal array). So after the first 2 responses you have data in the packets array as 0 and 1 as shown here:
```php
array(2) {
  [0] =>
  string(266) "I^Q[TR] Burak Oyunda Fun Sunucusu #Sunucuadresi.com\000surf_ski_2_GO\000csgo\000Sunucuadresi Hosties/Jailbreak\000<DA>^B^D6\000dl\000^A1.35.6.2\000<B1><87>i<89><B6>^L\000\000\0000^A!kni,!sunucuadresi,awp,cs,csgo,dr,fun,isyan !ws,isyancı,isyancılar,jail,jailbreak,jb,mg,public,surf,tr,turk,turkish,zm,zombie\000<DA>^B\000\000\000\000\000\000"
  [1] =>
  string(42) "D^D\000\000\000\000\000\000^S^]<92>A\000\000\000\000\000\000<ED>^L<B5>@\000\000\000\000\000\000<BB>f<B3>@\000\000\000\000\000\0001x<B1>@"
}
```
This is all fine and normal until the third response is processed which is the rules response.  This response comes back as a split packet which is usually the case due to all the settings and mods returned in the response.  The particular issue in this case is that the ID for the split packet being read using 
```php
$packet_id = $buffer->readInt32Signed();
```
Is also int(1) which is why it is throwing an error as you stated.   I am wondering why the packet id is so low in this case.  All the test runs I have seen have the number into the 2-5 digit range.  This would explain why the issue is so rare but it is an issue that has to be fixed.

In any case your proposed solution will not work as it overwrites the '1' index to reset to an array which causes you to lose the data that has already been set.  I will have to either go negative with all the single packet responses (if it can be done in PHP arrays) or make the split packets check to make sure the index it is trying to set does not exist before doing anything. I will build a test and make changes and see what I can come up with.
