### ISSUE TITLE
CSS Players Bug

### ISSUE THREAD

**Issue by lupikovoleg** [Austinb/GameQ#31]
Hi! I have bug with CSS query. Wrong players count.
Playing: 110/119, BUT REALLY 0/10 ! Please, tell me how i can fix it.

Sorry for my bad english.

**Comment by Austinb** [comment]
Hello,

What is the server information so I can test it?

Thanks,
Austin

**Comment by lupikovoleg** [comment]
nordost.su:27036

**Comment by lupikovoleg** [comment]
I'm doing some experiments, and see than in stand-alone, i have 0/10 players, but when i running GameQ in CodeIgniter Framework, i have 0/119. Also, only in CodeIgniter Framework i can't run gameq with Tf2 servers, and more than 1 source server.

**Comment by Austinb** [comment]
Sorry for the delayed response.  Been busy working and finding new work.

Try this code.  It is your server from above plus 2 I pulled randomly from gametracker.com. 

```
$gq = GameQ::factory();

$gq->setOption('timeout', 5)
    ->setOption('debug', TRUE)
    ->setFilter('normalise');

$servers = array(
    array(
        'type' => 'css',
        'host' => 'nordost.su:27036'
    ),
    array(
        'type' => 'css',
        'host' => '69.162.109.181:27015'
    ),
    array(
        'type' => 'tf2',
        'host' => '67.228.59.146:27015'
    ),
);

$gq->addServers( $servers );

$results = $gq->requestData();
print_r($results);
```

As far is being inside of a framework such as CodeIgniter without some PHP errors from CodeIgniter or PHP itself I am unable to debug anything.  In theroy you should be able to include the GameQ.php file anywhere and go.

**Comment by lupikovoleg** [comment]
as i sayed early, GameQ with debug not work.
also, i tried to use LGSL with CodeIgniter, and this bug is there.
so, i don't know what i should do, maybe debug gameq/lgsl with xDebug...

**Comment by Austinb** [comment]
Did you try that code I posted above?  Just from what you are saying it is something in CI causing the issue.  If the code above will work standalone it should work within a framework.  

Also the errors I am talking about will never be shown by GameQ.  White page errors are usually fatal errors (bad include, syntax error, etc...) from the PHP parser and are logged at the server/application level.  You will need to check the logs on the server, maybe CI has logs as well, and try to pinpoint what is causing those screens.  I cant be of more help without the actual errors from php because I will just be guessing.

Also I have used GameQ with Kohana 3 as a module and loaded it up that way.  If you are not doing it that way now in CI you might try it and see if it helps pinpoint the problem.

A simple php file with:

```
<?php
require_once('/path/to/GameQ.php');

(insert previous comment code here)

```

should work. You can also run the php file via the command line.
