### ISSUE TITLE
Ping per server (for TF2)

### ISSUE THREAD

**Issue by theChaosCoder** [Austinb/GameQ#314]
Is it possible to add a ping field per server for TF2?
something like [gq_ping] => 33 (would be in ms)

**Comment by lococoder** [comment]
Hey Chaos can you look at my post below how do i get the info to display I am not sure if i am missing something i tried to follow the documentation

**Comment by Austinb** [comment]
There is no ping part of GameQ at this point and there are currently no plans to add one.  Adding ping adds another call to the server.  Maybe possible to calculate it using the socket information available but at this point I am not sure if it is worth the time investing unless there is a large demand for it.  Also pinging physical servers has its own issues since the port for an icmp ping could be blocked by the network or server.

If users want to respond if this is something they want I can add it to the roadmap.

**Comment by theChaosCoder** [comment]
Couldn't it be just implemented as a "time measurement" somewhere in the doQueries() function?

**Comment by SOD96** [comment]
Just wondering. Why wouldn't you just ping that IP Address from your server and output that value during your calls for information?

**Comment by theChaosCoder** [comment]
What's how I'm doing it right now. 
I just saw that in some implementations (like here https://github.com/frostschutz/SourceLib/blob/master/SourceQuery.py) the developer just outputs the time diff. So I thought it wouldn't be too hard to implement. 

```
after = time.time()
..
result['ping'] = after - before
```

**Comment by Austinb** [comment]
@XenZibe A true ping would have to be an icmp call to the ip.  This may not work if the servers are set to drop icmp requests.  A lot of server companies do drop direct pings because they are an avenue for a dos attack.  Plus it is another network connection to the server, something I try to minimize in this library.

@theChaosCoder I can add something in the core system to time the calls and responses I am not sure how accurate it will be especially when querying multiple servers.  I will slate some time for this and see how reliable a timing mechanism is compared with a true ping.  Will make a new branch for it when I have something usable.
