### ISSUE TITLE
Can't add more than 1 CSS server

### ISSUE THREAD

**Issue by lupikovoleg** [Austinb/GameQ#32]
Hi!
I'm having trouble with adding more than one CS:Source server.
When i'm added first CSS server, GameQ is working (monitoring, servers). But, when i'm added second CSS server, GameQ isn't working. I'm seeing just white page, no more.

 i'm didn't have troubles with other servers, just with CSS. Help!

**Comment by Austinb** [comment]
Hello,

Can you paste the full call with both servers in it?  My guess is the white screen is a parsing error or other fatal error. 

Thanks,
Austin

**Comment by lupikovoleg** [comment]
I don't understand, what i should paste

**Comment by Austinb** [comment]
Paste whatever you are using to make the request to the CSS servers that is failing.  It is hard to figure out what is wrong without seeing the actual code making the request.

So should be $gq = new GameQ();
$servers = array(...)....

**Comment by lupikovoleg** [comment]
I'm connect your code with my php engine, where i'm using db, so servers array has this form:

```
    foreach($query as $k => $v)
    {
        $servers[] = array(
                    'type' => $v['protocol'], 
                    'host' => $v['host'] . ':' . $v['port'], 
                    'id'   => $v['title']);
    }

    $this->setOption('timeout', 1);
    $this->setFilter('normalise');
    $this->addServers($servers);
```

**Comment by Austinb** [comment]
Comment out the id => part or change it to be a regular string.  The Id was not designed for anything other than simple strings of letter, numbers, underscores, etc... So something like 127.0.0.1:27015 or a hash like a67453fe2.... The idea being so that you can pick out the results for the specific server by that id instead of needing to iterate over the results array.

Also after you populate the $servers array print_r it out and make sure type and host are being set and not empty.

One last thing set debug on $this->setOption('debug', TRUE); and see if that gives you any errors.  If not and you are still getting a white page check your php error log and see what is happening. 

Sorry I can not be more specific but it is hard without seeing the actual extending class and the data being added to the array. Let me know what you find.

**Comment by lupikovoleg** [comment]
Id in servers have html tags....

When i'm enabled debug, i'm seeing white page.

**Comment by Austinb** [comment]
Check your php log. If nothing pass me the server info for 2 of the servers in the list causing the issue.  I can check it out this evening (US time) and see if something is specifically related to your other ticket (#31)

**Comment by lupikovoleg** [comment]
I'm tried to use hash in ID, but it's doesn't work.

**Comment by AmkCity** [comment]
I have all the good work can be seen in http://amursk-portal.ru/main/game-servers/#7

**Comment by Austinb** [comment]
Cool.  Glad you got it to work.  What was the issue?

**Comment by AmkCity** [comment]
Perhaps it uses global variables, and are superimposed on the server in the following list
