### ISSUE TITLE
Notice: fwrite() and Fatal Error

### ISSUE THREAD

**Issue by CaptainJackas** [Austinb/GameQ#340]
Hi there,

I'm having a problem when running through a list of around 2000 servers. I know that around 200 of those are not always online so sometimes when in scan them there're offline. Now I don't know if that has anything to do with my problem but everytime I scan all servers it gives me a notification:

Notice: fwrite(): send of 7 bytes failed with errno=111 Connection refused in /var/www/vhosts/site/httpdocs/src/GameQ/Query/Native.php on line 65

Sometimes it only gives this message once, the other time it gives it twice but it always _succesfully_ scans all servers (even with hundreds of offline servers). But when I scan even more servers (3k+) I receive this notice three times followed by a fatal error where the scanning stops:

Notice: fwrite(): send of 7 bytes failed with errno=111 Connection refused in /var/www/vhosts/site/httpdocs/src/GameQ/Query/Native.php on line 65

Fatal error: [] operator not supported for strings in /var/www/vhosts/site/httpdocs/src/GameQ/Protocols/Source.php on line 185

What does this mean and how do I solve this?

**Comment by Austinb** [comment]
Sorry for the delayed response.

The error of Connection refused usually refers to the networking side where the connection trying to be made to the server to send the status packets was actively refused.  This could be due to a firewall or possibly anti-ddos measures if you are requesting status updates too frequently. 

The script should skip over this and report the server as down.  Do you have the type of server that is being refused?  Is it the same set of servers or is it random?

**Comment by Austinb** [comment]
Please open this issue back up if you are able to provide more information.

**Comment by P4sca1** [comment]
I do have the same problem sometimes. It is always the same set of servers (mostly gmod, 2 ark servers).
The error occurs randomly.

**Comment by MrMatew** [comment]
Same error with gmod and minecraft servers. @Austinb , can you help or give an advice?
Btw GameQ v2 works well, v3 - this error
![clip2net_170724220550](https://user-images.githubusercontent.com/5469484/28539986-5459538e-70bc-11e7-83ce-c41a0823f905.png)
