### ISSUE TITLE
Add Server

### ISSUE THREAD

**Issue by TacTicToe66** [Austinb/GameQ#344]
Can you add support for Battlefield Bad Company 2? 

Query info is in V2, 

Thanks!

**Comment by TacTicToe66** [comment]
Is this still being developed? I would think my BC2 request would be a fairly simple one. Convert your previous versions BC2 to V3. Not sure why BF2 and BF1942 are included and BC2 wasnt to begin with.

**Comment by TacTicToe66** [comment]
Hi Austin-

You had this working in a previous version. Is it possible to get it converted?

**Comment by Austinb** [comment]
There is no ordering for the response packets coming back for this protocol.  I made a note about it in the files.  If a server does not return the response in the same order as they were sent in it will cause the response to break.  But it works fine so long as the order is unchanged.

**Comment by TacTicToe66** [comment]
Seems to work on my site. Thank you. 

Question. Is it possible to rename the returned map names in this protocol script? Or is that something that should be done elsewhere? 

For example - map name is returned as "Levels/MP_007GR" which is impossible to name a map image as. In my LGSL script this was renamed to the descriptive name "White Pass". 

Thanks again for your work.

**Comment by Austinb** [comment]
@TacTicToe66 This library is limited to just returning the server information passed to it.  In some cases I will build in some normalization for specific servers but not for maps as a general rule.  Usually games have a lot of maps and in some case hundreds due to custom maps being allowed and it is hard to keep the list updated.  For now I would recommend building an association some where with the value returned by GameQ and the one you want to be displayed in your listing.  If you have a complete list of the map server values and their more descriptive values please open up a new issue and I will take a look at it. 

It may be possible to add some kind of general association library to keep the maps updated, and possibly other properties,  outside of the actual protocol classes but I am not sure on how well that would work.  Also I am unsure of the speed/memory penalties if that library got be a decent file size.  Another option would be to build it as part of the normalization filter.

**Comment by Austinb** [comment]
Another option is to string replace the "/" with a "_" before printing/echoing out the value of that field.  That would allow you to name the file name for the map image as an example.  You may also want to strtolower() that value just so you do not have to deal with case when trying to reference the images.
