### ISSUE TITLE
don't show results for every server

### ISSUE THREAD

**Issue by Supryk** [Austinb/GameQ#348]
Why GameQ don't show results for every server? lose first csgo
`Array
(
    [0] => Array
        (
            [type] => minecraft
            [host] => 151.80.111.8:26851
            [options] => Array
                (
                    [query_port] => 26851
                )

        )

    [1] => Array
        (
            [type] => csgo
            [host] => 193.33.176.75:27105
        )

    [2] => Array
        (
            [type] => csgo
            [host] => 193.33.176.75:27058
        )

    [3] => Array
        (
            [type] => teamspeak3
            [host] => 92.222.69.101:9987
            [options] => Array
                (
                    [query_port] => 42069
                )

        )

)`

**Comment by Austinb** [comment]
How often are you requesting statuses from those servers?  What are the pings from your host where the script is to the servers?

I tested both servers in that list and both came back with results.

**Comment by Supryk** [comment]
if I check each individual - it is ok
but together one server missing

**Comment by Austinb** [comment]
I was able to ping those servers multiple times all in the same call.  It is possible you may need to tweak the timeouts and/or write wait settings (https://github.com/Austinb/GameQ/wiki/Configuration%20v3#advanced-settings) and increase them a bit.  The stream_timeout timeout  should be a larger or larger than the server with the largest ping.  

The only other issue is the data coming back is being dropped due to a firewall or network issues.  Have you run this list with debug enabled?  Do you receive any errors when pinging this list in debug mode?

```php
$servers = [
    [
        'type' => 'csgo',
        'host' => '193.33.176.75:27105',
    ],
    [
        'type' => 'csgo',
        'host' => '193.33.176.75:27058',
    ],
    [
        'type'    => 'minecraft',
        'host'    => '151.80.111.8:26851',
        'options' => [
            'query_port' => 26851,
        ],
    ],
    [
        'type'    => 'teamspeak3',
        'host'    => '92.222.69.101:9987',
        'options' => [
            'query_port' => 42069,
        ],
    ],
];

$gq->addServers($servers);
```

**Comment by Austinb** [comment]
If you have any more information please reopen this issue.
