### ISSUE TITLE
Frontlines Fuel of War

### ISSUE THREAD

**Issue by TacTicToe66** [Austinb/GameQ#353]
This was in your V2 I believe. Can you port it to your latest? I tried but porting doesnt seem to be very straight forward. Here is some info

Game port default = 5476
Query port = 5478

I am going to idle in one of our servers until I get a response from you, so it will show a player on the server

IP:  104.153.104.205

These servers can be queried because they show up on Gametracker and when I use LGSL. 

Thanks!

<a href="http://www.gametracker.com/server_info/104.153.104.205:5476/" target="_blank"><img src="http://cache.www.gametracker.com/server_info/104.153.104.205:5476/b_560_95_1.png" border="0" width="560" height="95" alt=""/></a>

**Comment by Austinb** [comment]
How active is this game?  I only ask because it will require a few hours of time to port into the v3 protocols on how packets are sent and received.  I checked Gametracker and I only see 4 servers all of which are currently empty.

**Comment by TacTicToe66** [comment]
Less active then we would like. There is a group of us trying to change that atm. Do you have a blank template that I can see what needs to be changed? There are so many versions of GameQ now it is becoming confusing.  You had this protocol working in a previous version. I was hoping it was just a simple port like you did with BC2. I am happy to compensate you for your time if you like, if you have like a Paypal account or something? 

There are other games I would like to see ported as well. ETQW is not working either. If you had a template it would make importing things easier. If I knew what variables are changing etc, I could make the changes myself and just add them as commits and not need to bother you.

**Comment by Austinb** [comment]
The majority of the time spent moving a previously supported protocol into v3 is on the responses coming back from the server after being queried.  In version 2 each packet sent got its own dedicated connection to the server so when the response came back on that connection the library knew which packet the response belonged to. In the case of FFOW (and a few others) the packets were sent in turn meaning that a packet was sent and a response was waited for before the next packet was sent. This makes it really easy to know which response belongs to which query request but is slower and less efficient. 

To increase the querying speed and efficiency this model was changed in version 3 to send all of the packets in succession to the server on a single connection.  This means that the responses can come back out of order at which point they have to be deciphered usually by the header of the packet (first few bytes) as to which call the response belongs to.  Because of this there is no real easy way to make a template to build out new support as each one is different and each have their own quirks. As for the versions, v3 is the only one I am working on actively.  Version 1 is still here just for history for some really old protocols.  I know some people still use v2 but I have not updated it in quite some time. 

As far as money goes if you wish you donate you may do so using the link on the README.md or in the wiki but I do not expect payment to get features/games  added.  This is a project I started as part of a previous job that has just become something to work on in my free time for fun. 

I will look into ffow today and see how straight forward the responses are.  For any other games you wish to have ported into v3 please open up new issues for each one you want added.  It make take a bit of time but eventually they can all be added assuming there are active servers to test against.

**Comment by Austinb** [comment]
Pretty straight forward so changes incoming.

On a side note the original v2 protocol is missing support for players (https://github.com/Austinb/GameQ/blob/v2/gameq/protocols/ffow.php).  Same issue as now, no servers with any active players to test against to build it.

**Comment by Austinb** [comment]
Added in 2fd84067d6ab37a6ac5edcb40c7e9f30d2a43c0a
