### ISSUE TITLE
Gta Network 

### ISSUE THREAD

**Issue by rststeam** [Austinb/GameQ#362]
Hi, there is a new Multiplayer https://gtanet.work/ for GTA V , could you please make it.  I asked owner he said use https://master.gtanet.work/apiservers then filter it or use UDP. Thanks

**Comment by rststeam** [comment]
I have made some filtering of above 

https://multiplayerhosting.info/gtan/api.php?ip=213.32.73.58:4499
https://multiplayerhosting.info/gtan/api.php?ip=213.32.73.58:4499&raw
https://multiplayerhosting.info/gtan/api.php?ip=213.32.73.58:4499&banner5=true

But i don't know how to read packet info. Thanks

**Comment by Austinb** [comment]
Raw JSON response needs raw query param - https://multiplayerhosting.info/gtan/api.php?ip=134.255.231.233:4499&raw

**Comment by Austinb** [comment]
From the data on the master list it looks like the network is not really used much.  I have built it out in another branch because of changes required to the core for SSL responses. Please checkout and use faa2017 and use it with other games to make sure there are no issues with the socket read change.  Unit testing does not cover actual socket reading/writing.

**Comment by Austinb** [comment]
Has anyone had a chance to pull that branch and check it out.  I am going to pull it into the v3 stream soon along with some other changes.  Please test and let me know if it does not work or if it breaks other protocols.

**Comment by Austinb** [comment]
Merged into main at 40d4729cdbee7f0e69dea44f63cbdb002aeae73f.  Please open a new issue if you have any issues querying.
