### ISSUE TITLE
Grab Steam ID of players in a server?

### ISSUE THREAD

**Issue by jljr222** [Austinb/GameQ#372]
Is it possible to grab the Steam ID of a player on the server? I was looking through the documentation, examples and issues, but couldn't find if this was possible. Apologies if this has been asked already!

**Comment by Stormyy** [comment]
Depends on the game your trying to query. Most games don't give that information about a player. What game are you trying to query?

**Comment by jljr222** [comment]
CSGO would be the game.

**Comment by Austinb** [comment]
@jljr222 All the information provided by the servers is returned as part of the response.  The actual A2S (source) protocol specification does not have an entry for Steam ID - https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_2.  My guess is due to the public access of the player information they did not want to expose the Steam ID for the users much like games that used to return IP address information of players no longer do.
