### ISSUE TITLE
LAN server searching

### ISSUE THREAD

**Issue by travispk** [Austinb/GameQ#373]
For our LAN Party events we built GameQ into our Intranet site.  Where attendees can go and manually add servers with a form.  Along with a cronjob, we query the list of servers and present them on the Intranet site.  I'd love to be able to have GameQ search the LAN for game servers and add them to the list/database.  Possible to add support for GameQ to do a network broadcast and look at the responses that come back from the game servers and return that result?

**Comment by Austinb** [comment]
@travispk There is no scanning ability in this library mainly because it would not work in most cases and would probably cause people using it to get blocked by firewalls.  I could see where a internal LAN network would benefit from auto-discovering game servers but it is beyond the scope of this library.  There may be other standalone programs that would let you scan but I am not aware of any.

**Comment by travispk** [comment]
Like I explained above (please reread), this would exactly be for LANs only and it's not really a "scan".  You send out a broadcast to 255.255.255.255 and then listen to the unicast responses from the game servers on the network.  I don't believe this would be possible outside of the library, this functionality would need to be integrated into the library.  There are standalone apps that do this, hlsw.net for one.  But they are no longer supported and are getting out of date.  As well, that is not web based like I want this solution to be.

I just released my gamebride solution onto github that resends game broadcasts across VLANs.  I created this to solve this problem at huge LAN events that I run.
https://github.com/travispk/gamebridge
