### ISSUE TITLE
DayZ Standalone Not Working

### ISSUE THREAD

**Issue by firefly2442** [Austinb/GameQ#392]
Original issue: https://github.com/Austinb/GameQ/issues/370

Wasn't able to re-open existing issue.

**Comment by Austinb** [comment]
Need a server or set of servers with ports (both connect and query) to test against.   Are you able to query any type of server?

**Comment by firefly2442** [comment]
https://www.gametracker.com/search/dayz/

Server example: 206.217.139.50:2502

Based on the current sourcecode, the query port is derived from the client port:

https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Dayz.php#L64

I am able to query and show other servers, such as Arma 3.

**Comment by Austinb** [comment]
I am unable to query that one either.  I was able to query this random server from gametracker - 108.174.57.251:2302.  Please test that one and let me know. 

The query port derivation is just an attempt to make life easier by guessing at what the port should be based on defaults for that game.  There are many cases where you will need to pass a query_port parameter for the server because the server owner changed they query port.   If you do not know the query port and it is not responding on the defaults either the port was changed or the server is blocking/dropping any traffic to the query port.

**Comment by firefly2442** [comment]
Seems to work, thanks for the help.  Code for future reference:

https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Server.php#L49

And the wiki:

https://github.com/Austinb/GameQ/wiki/Examples-v3#different-client-and-query-ports
