### ISSUE TITLE
Processing large amount of servers

### ISSUE THREAD

**Issue by shyim** [Austinb/GameQ#400]
Hey,
i am currently passing 60 servers at once to GameQ and getting the results the first 20 records are right, but after them all servers are offline. I changed my timeout from 4 seconds to 60 seconds and this doesn't help.
My current solution is array_chunking my gameserver array and create for any 10 servers a new GameQ instance, which solves the Issue. Is there known Issue with querying multiple servers?

**Comment by Austinb** [comment]
There is a known limitation within the core query code due to how PHP handles sockets (not very well) which can cause larger lists to not fill out correctly.  You can try messing with the "stream_timeout" setting and increase its value to see if that helps.  More settings are available at https://github.com/Austinb/GameQ/wiki/Configuration-v3#advanced-settings.  Depending on the average response time you may want to run your servers in blocks with the largest ping servers all grouped together and then on down. 

I am looking for help in making the code faster without affecting the returns for a few servers.  Whether it is with the native PHP code or with using a module you have to install.  I rebuilt the query core in v3 to allow for swapping out of the query mechanism but I have not had time to test any other methods for querying either built in or PHP extensions.
