### ISSUE TITLE
ARMA 2 & ARMA 3 issue

### ISSUE THREAD

**Issue by Gasjki** [Austinb/GameQ#407]
Hi. I tried to query first 5 servers from gametracker.com of Arma 2, but all I get is : 

`array(1) { ["45.121.211.29:2312"]=> array(19) { ["gq_address"]=> string(13) "45.121.211.29" ["gq_dedicated"]=> NULL ["gq_gametype"]=> NULL ["gq_hostname"]=> NULL ["gq_joinlink"]=> string(35) "steam://connect/45.121.211.29:2312/" ["gq_mapname"]=> NULL ["gq_maxplayers"]=> NULL ["gq_mod"]=> NULL ["gq_name"]=> string(6) "ARMA 2" ["gq_numplayers"]=> NULL ["gq_online"]=> bool(false) ["gq_password"]=> NULL ["gq_port_client"]=> int(2312) ["gq_port_query"]=> int(2304) ["gq_protocol"]=> string(6) "source" ["gq_transport"]=> string(3) "udp" ["gq_type"]=> string(5) "arma2" ["players"]=> array(0) { } ["teams"]=> array(0) { } } } `

I search for query port, I tried all of them but I get the same error. I have latest version of GameQ. Any idea why ? I have fsockopen activated because I tested over 15 games before this happened.

EDIT: Same problem for ARMA III too.

**Comment by Austinb** [comment]
Its is likely they are either blocking the query ports or have changed them (if the game allows them to).  I tested a few and got this one to work as expected - 107.191.44.98:2302.  Please try that one. If you are having issues still it is likely there is an issue with your host not allowing the outgoing query calls due to firewall policy.
