### ISSUE TITLE
Minecraft response array error

### ISSUE THREAD

**Issue by Meathoook** [Austinb/GameQ#408]
This worked for me before but when I updated the code the response i get from a Minecraft server looks like this:

`Array ( [] => Array ( [0] => Array ( [] => map ) [1] => Array ( [] => world ) [2] => Array ( [] => numplayers ) [3] => Array ( [] => 0 ) [4] => Array ( [] => maxplayers ) [5] => Array ( [] => 4 ) [6] => Array ( [] => hostport ) [7] => Array ( [] => 25565 ) [8] => Array ( [] => hostip ) [9] => Array ( [] => 127.0.0.1  ) ) [1.12] => plugins [MINECRAFT] => version [SMP] => game_id [gq_address] => 127.0.0.1 [gq_dedicated] => [gq_gametype] => [gq_hostname] => gametype [gq_joinlink] => minecraft://127.0.0.1:25565/ [gq_mapname] => [gq_maxplayers] => [gq_name] => Minecraft [gq_numplayers] => [gq_online] => 1 [gq_password] => [gq_port_client] => 25565 [gq_port_query] => 25565 [gq_protocol] => gamespy3 [gq_transport] => udp [gq_type] => minecraft [hostname] => gametype [players] => Array ( ) [teams] => Array ( ) )`

Noticed the latest changes to protocol Gamespy3.php added a preg_replace pattern with double quote. I changed it to single quote and it worked for me but the double quote was maybe intentional.

**Comment by Austinb** [comment]
Is the server available online to ping? If so please provide the info so I can test and build a unit test for it. Gamespy 3 is quirky and has issues if the response is incomplete or the server decides to mangle the response a bit.

**Comment by Meathoook** [comment]
I've sent you an email with some information.

**Comment by Austinb** [comment]
Just from a quick glance at the response it appears the empty hostname is causing the process to quit out too early.  GS3 is a very annoying protocol because different servers return slightly different responses.   The short term fix is to set a hostname for your server. 

The response from your server looks like this:

```bash
hostname\000\000gametype\000SMP\000game_id\000MINECRAFT\000version\0001.12.2\000plugins\000\000map\000world\000numplayers\0000\000maxplayers\0004\000hostport\00025565\000hostip\000127.0.0.1\000\000^Aplayer_\000\000\000
```

You can see the hostname is empty after the \x00 entry for the key.  Because of that it thinks the processing of the server parameters is done and is moving on to the player info instead of further down before the "player_" section.  I will see if I can try to use the ^A break point but if I recall that value was not always the same across the different servers that use GS3/4. I maybe able to use regular expression and use a wildcard for that spot.   Will have to try, test and see if it breaks anything else.

**Comment by Austinb** [comment]
I have changed the way GS3 is done to remove the hacky preg_replace code in favor of splitting the data like it should have been.  I had to get some new test servers as there was bad test data.  Also had to tweak Justcause 2 because it decided to break protocol (or GS4 is actually different but cant find any info on it). 

Please pull down v3-dev and let me know if it fixes your issue.  Feel free to reopen this issue if not.

**Comment by Austinb** [comment]
See 9aaf4b0
