### ISSUE TITLE
Old games from GameQ v1

### ISSUE THREAD

**Issue by Hembi** [Austinb/GameQ#425]
Hi,
Can you implement the old games' protocols from the GameQ v1 branch to the new version?

**Comment by TacTicToe66** [comment]
Can you be a little more specific?

**Comment by Austinb** [comment]
@Hembi If you have specific requests please open one issue per game.  Many of the games were not brought forward due to age and lack of servers to test against.  Also if you feel inclined you may write your own implementations and then send pull requests.   

Please open a new issue for each game you are wanting to be added.  Just fyi if there is no way for me to test it for data it probably will not be added into the library.
