### ISSUE TITLE
Bzip2 and zlib

### ISSUE THREAD

**Issue by zeagon** [Austinb/GameQ#43]
Hey, ive seen in the requirements that these 2 are required, but iam planning to integrate this into a prooduct ( have it working )

On my test site i dont have bzip2 and zlib, i commented out the requirement check error.

Anything else i should comment out so it dont come to errors regarding this 2?
I assume it runs a lot slower without it?
anyway to speed it up without these 2?

So far iam having no issues beside speed with this great script and ips where the servers query port is different than the default games port / is not setup correctly.

Thank you,
Seb

**Comment by Austinb** [comment]
Bzip2 is used to decompress A2S compressed responses, mainly the rules query response for Steam based games.

Zlib was used for America's Army 3 to decompress the response from the server but this was before 3.2.  I am planning on removing the zlib requirement sometime soon, or moving it to the pre3.2 class file.  As of 3.2 AA3 now uses A2S for its queries. 

As far as removing the check that is fine, there is a minimal speed increase from removing the check but if you try to query a server that has a compressed A2S response it will error out at line 339 in the protocols/source.php file because the function bzdecompress() will not exist.

If others want it I can move the bzip2 check into the actual source protocol class and if bzip2 does not exist I can make the data come back as empty.

**Comment by zeagon** [comment]
I think this would make more sense than spitting out an error. Or only let the error appear in debug mode.
For the time beeing i also comment out the possible exception in the function you mentioned to avoid those errors to appear on my users sites.

As for speeding things up ive planned to only query gq_online and gq_num/maxplayers.
At first i thought i could add it to the gq->requestData(); part while initializing, but dont get it to work.
Something along the lines of gq->requestData('gq_online'); and only pulls that from the server. Havent studied the code very deeply yet, but i guess that just wont work
Removing the parts in the protocols (source etc) would accomplish this i guess, but might be a bit overboard and makes updating a horror.

As it stands now i need to query a minimum of 10 server per page, which really kills my page. Properbly due the fact that the initiliazing happens 10 times, which i should avoid, but havent found a way around it since i need to set the servers before the rest. But ill find a way around that, iam sure.

**Comment by Austinb** [comment]
All of the protocols respond with more data than just what you are looking for.  In most cases the general query returns a lot of info about the server like map, players, time left, etc... it is just the way they were written.  As far as pulling out specific info that can be done easily from the returned information array but there is no way to query the server for just players, max players and nothing more. 

In the case of some there is a challenge requirement which means you have to send a challenge to the server and read the response before you can query any information from the server.  Source is the best example of this.

For multiple servers make sure you are passing the all of the servers at once using addServers and using the same instance you created the first time.  Instancing the class does not do a lot since other classes are not loaded until you request the actual data.  

As far as using this in a web site I would highly recommend some kind of caching mechanism like memcache to sit in between the php script and the call to the actual GameQ class. I would also use a cache timeout of at least 1 minute if not more. The server query protocols are not built for real-time server information and in some cases will actually temporarily block ips if they send too many query requests in a given amount of time due to a perceived dos attempt on the server.

**Comment by Austinb** [comment]
Also for speed see #24 as I am trying to speed up the internals as much as possible.
