### ISSUE TITLE
ARK: Survival Evolved | Query Port

### ISSUE THREAD

**Issue by ViperAix** [Austinb/GameQ#446]
`
    protected $port_diff = 19238; 
`
This isn't correct. 

See: https://ark.gamepedia.com/Dedicated_Server_Setup#Network

**Comment by Austinb** [comment]
Unless the default query port has changed, which it does not look like it has, that is the correct offset to get the query port (27015) from the client port (7777).  You pass the client connect port with is 7777 by default and it does the math for the default query port, 7777 + 19238 = 27015. 

If the math doesn't work because the server's ports are different than the default then the query port will need to be specified to get the information.  Please open this issue back up if the defaults have changed.
