### ISSUE TITLE
Conan Exiles | Query Port

### ISSUE THREAD

**Issue by ViperAix** [Austinb/GameQ#447]
The Query port is 27015 (Steam-Queryport)

https://www.conanexiles.com/de/blog/einrichtung-deines-eigenen-servers-conan-exiles/

**Comment by Austinb** [comment]
This game is the same as the other base Source games (CSS, CS:GO, etc...) where the client and query ports are the same.  Not sure what the issue is here.  Please open if you have a specific issue getting information from a Conan Exiles server. 

By default you have to pass the client port of the server with the ip address.  So 127.0.0.1:27015 as an example.  If you have other usage issues I would recommend reading through the v3 wiki pages - https://github.com/Austinb/GameQ/wiki/Examples-v3
