### ISSUE TITLE
Source::processResponse response type 'A' is not valid

### ISSUE THREAD

**Issue by Mo45** [Austinb/GameQ#452]
Hello, When I try to get data from the server, I get this error:

<pre>Fatal error: Uncaught GameQ\Exception\Protocol: GameQ\Protocols\Source::processResponse response type 'A' is not valid in /home/mo45/www/rust/htdocs/GameQ/src/GameQ/Protocols/Source.php:207</pre>

However, if I repeat the request for the same server 2-3 times, the data will be successfully received.

The code of the file that receives the data.

```
ini_set('display_errors', 1);
require_once(__DIR__ . '/src/GameQ/Autoloader.php');

$server = "164.132.206.228:28026";

$servers = [
    [
    'type'    => 'rust',
    'host'    =>  $server,
    ]
];

$GameQ = new \GameQ\GameQ();
$GameQ->addServers($servers);
$GameQ->setOption('debug', true);
$GameQ->setOption('timeout', 5);
$GameQ->addFilter('secondstohuman');
$GameQ->addFilter('stripcolors');
$GameQ->addFilter('normalize');

$results = $GameQ->process();
print_r($results);

```

Is this a bug in the script, or the configuration of my server?

**Comment by Austinb** [comment]
That response is usually due to an incomplete packet or response from the actual server.  Since the header for the packet is missing or is wrong the library throws an error.  You can suppress this error by disabling the debug setting but the server will show up as offline in the results list. As much as I have looked I have been unable to find a solution. 

Please let us know if you are able to replicate the issue consistently.
