### ISSUE TITLE
[DAYZ] Display just users online

### ISSUE THREAD

**Issue by cal3by** [Austinb/GameQ#455]
On my website I have a box where it shows all information which I wanted, but i also wanted just to have users online somewhere else on the page as well is there anyway to do that I tried to copy the PHP code to do that but it just says /, any help would be amazing thank you (Website is survivalz.org

**Comment by Gasjki** [comment]
No one is gonna give you the code, so you have to work on it. But, instead of asking and waiting for code I'll give you some advice: My guess is that you are not saving your query data (which is bad). So, in this case you have two options: start using a database and a cronjob to query this server regularly or save query information to a global variable and access it anywhere you want. Good luck! @Austinb should close this ticket because there's no issue or feature requested.

**Comment by Austinb** [comment]
If you have a specific bug or issue you are unable to over come please open this issue back up.  Without more information as to what the issue specifically is I am unable to provide any assistance.
