### ISSUE TITLE
Add default ports

### ISSUE THREAD

**Issue by droutin** [Austinb/GameQ#463]
Hi, Is there a chance to have default ports for game servers? In the host will be only ip without port. Another request is support for DNS SRV. In the host will be again only dns address without port.

**Comment by Austinb** [comment]
Version 3 was changed from version 2 so that the client connect port at a minimum is required to be provided.  In some cases the query port is required as well if it is not a standard port based off of the client connect port's value or if the query port has been customized.  There is no plan to go back to having default ports. 

There are no plans to add any other network level functionality to this library.  It would be simple to add a wrapper that pulls down the DNS records and then uses the proper record and port and passes that to the servers array before that list is passed to GameQ for processing.  If there is a clean way to add that functionality as a filter (or pre-filter) it could be included in the library as such but would add more time to process the server list due to the extra work having to do DNS record pull and iteration.   I am not aware of anyone using the SRV records for connecting to servers since the client port usually has to be explicitly passed when launching a game from a url for example.

Please feel free to open a new issue if you have a working prototype of SRV integration.
