### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by WilcoGamer** [Austinb/GameQ#482]
Is it possible to add discord so it can query the people on the server and people online ?

**Comment by aidanrico** [comment]
What do you mean?

**Comment by WilcoGamer** [comment]
I wish to pull the numbers from a discord server using GameQ @aidanrico

**Comment by Austinb** [comment]
I do not believe there is a way to integrate without going through the Discord API.   Since there is no "simple" way to query the server information using the existing structure this is a more involved support request.  If anyone has any thoughts on this please feel free to reopen or comment on this issue.  For not going to close it as I do not have the bandwidth to take on this integration.

**Comment by PurpleTape** [comment]
Hello Austinb!

Found it here: https://github.com/Rapptz/discord.py/issues/33#issue-114486646
> Discord provides "Widget"'s API which allows anyone with server ID to collect general info on server (channels, members, etc). Also has invite url.
> 
> API endpoint is `https://discordapp.com/api/servers/{server.id}/widget.json`
> Example: https://discordapp.com/api/servers/94367845990805504/widget.json
> 
> For Widgets to work anyone with `Manage Server` permission must enable it under `Server Settings > Widget` tab.

What do you think about getting discord server information via http (tcp)?

Thanks!
