### ISSUE TITLE
Problem sending traffic

### ISSUE THREAD

**Issue by mokstory** [Austinb/GameQ#499]
I have a virtual machine with two virtual network interfaces.
On the first interface, I have a gray network - 192.168.1.200.
On the second interface, I have a white network - 176.12.33.34.

The PHP script is being executed for me on the default route of the gray network, I need to run on white.
There are some difficulties with routes for the white network, so I’m looking for an alternative.

Why is the standard not provided for the situation of sending packets from a specific ip, and not from the default route?

**Comment by mokstory** [comment]
@Austinb

**Comment by Austinb** [comment]
Well the issue is probably the priority of the devices on the server and which IP the script should bind to.  For the majority of use cases it doesn't matter which IP to bind to because they all can access the internet. You will have to make a change to the Query/Native class and add in the correct IP to use instead of using `0:0` which is what is hard coded into the class. Specifically at https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Query/Native.php#L97 you can change it to something like `127.0.0.1:0` for any available port on the loopback address for example. 

There maybe other ways to keep the `0:0` in there and change the priority of the interface being used but that would likely have to be a OS level setting/change. I am not aware of any option to make PHP use a specific network interface by default when it makes outgoing requests for functions such as `file_get_contents()` or cURL.  PHP may just pull the first external interface out of the list from `ifconfig -a` or something similar.

Last option would be to add a setting into the core for the query classes that allows you to pass the `bindto` ip:port that defaults to `0:0`.  Feel free to make the change and submit a pull request if you have the time. 

References:

- https://stackoverflow.com/questions/4150122/how-to-bind-stream-socket-client-to-an-interface-in-php
- https://www.php.net/manual/en/context.socket.php
