### ISSUE TITLE
Terraria not working?

### ISSUE THREAD

**Issue by byluz** [Austinb/GameQ#503]
Hi so I have been trying to query Terraria but it does not seem to be working? Can someone please test so we can confirm it is or is not working!

Thanks!

**Comment by gangscape** [comment]
Works fine for me, try with this server for example: terraformserver.com:7777

**Comment by Austinb** [comment]
Need more information such as servers you are trying to connect.  Have you tried different servers from https://terraria-servers.com/?

**Comment by byluz** [comment]
> Need more information such as servers you are trying to connect. Have you tried different servers from https://terraria-servers.com/?

Yeah I have tried 4 from that website. All are still saying offline.

Here are some I tested and are showing offline:
t.dark-gaming.com:7777
pedguin.com:7777
t.teeria.eu:7777

**Comment by Austinb** [comment]
When testing random servers it is best to have debug enabled so you can see any errors - `$GameQ->setOption('debug', true)`.  With many of those servers you will see the connection being refused or timing out.  This is due to either a bad query port because the server changed the query port to something other than the standard or the server/network has a firewall in place dropping any requests to the query port.  

Requests work fine for the following servers:
- ter.rencorner.com:7777
- ter.rencorner.com:7779
