### ISSUE TITLE
Returning an empty array

### ISSUE THREAD

**Issue by tommyvange** [Austinb/GameQ#507]
Hello, I am having a bit of a weird issue. Whenever I try to QUERY my server, this script just returns an empty array.

My code:
```
<?php
require_once('Autoloader.php');

$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
    'type'    => 'rust',
    'host'    => '136.243.95.38:28015',
    'options' => [
        'query_port' => 28016,
    ],
]);

$GameQ = new \GameQ\GameQ(); // or $GameQ = \GameQ\GameQ::factory();
$GameQ->setOption('timeout', 5); // seconds
$GameQ->addFilter('normalize');
$GameQ->addFilter('secondstohuman');
$GameQ->addFilter('stripcolors');


$results = $GameQ->process();
print_r($results);
?>
```

What the website is returning:
`Array ( )`

I have tried to run the code in both PHP 5.6 and 7.2 but neither made any difference. I am using GameQ version: `3.0.14`. PHP errors are also enabled, but there is nothing showing up.

Please help me, as I am completely lost.

Thanks,
Tommy Vange

**Comment by uilson** [comment]
Hi, you have the wrong query port.
Remove the options field from the request, your server query port is the port in the host field, so you don't need the options part.

> $GameQ->addServer([
>     'type'    => 'rust',
>     'host'    => '136.243.95.38:28015',
> ]);

**Comment by tommyvange** [comment]
> Hi, you have the wrong query port.
> Remove the options field from the request, your server query port is the port in the host field, so you don't need the options part.
> 
> > $GameQ->addServer([
> > 'type'    => 'rust',
> > 'host'    => '136.243.95.38:28015',
> > ]);

Hello, and thanks for getting back to me! 

I changed it to this:
```
<?php
require_once('Autoloader.php');

$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
    'type'    => 'rust',
    'host'    => '136.243.95.38:28016',
]);

$GameQ = new \GameQ\GameQ(); // or $GameQ = \GameQ\GameQ::factory();
$GameQ->setOption('timeout', 5); // seconds
$GameQ->addFilter('normalize');
$GameQ->addFilter('secondstohuman');
$GameQ->addFilter('stripcolors');


$results = $GameQ->process();
print_r($results);
?>
```

But I am still just getting an empty array :(

**Comment by uilson** [comment]
Now that I had time, I have taken a second look at the code, and you ave things wrong in your code
Like i told you before your game query port is 28015 not 28016 so you don't need the options in the server array.

You have this:
> $GameQ->addServer([
>     'type'    => 'rust',
>     'host'    => '136.243.95.38:28015',
>     _**'options' => [**
>         **'query_port' => 28016,**
>     **],**_
> ]);

it needs to be:

> $GameQ->addServer([
> 'type' => 'rust',
> 'host' => '136.243.95.38:28015',
> ]);
----
Now the second problem, you either didn't follow the example in the [wiki](https://github.com/Austinb/GameQ/wiki/Examples-v3) section, or you got confused while following it.

In your replay you have this:
> Hello, and thanks for getting back to me!
> I changed it to this:
> ```
><?php
> require_once('Autoloader.php');
> 
> $GameQ = new \GameQ\GameQ();
> $GameQ->addServer([
>     'type'    => 'rust',
>     'host'    => '136.243.95.38:28016',
> ]);
> 
> $GameQ = new \GameQ\GameQ(); // or $GameQ = \GameQ\GameQ::factory();
> $GameQ->setOption('timeout', 5); // seconds
> $GameQ->addFilter('normalize');
> $GameQ->addFilter('secondstohuman');
> $GameQ->addFilter('stripcolors');
> 
> $results = $GameQ->process();
> print_r($results);
> ?>
> ```
> But I am still just getting an empty array :(

Here's whats wrong, in your code, at the beginning, you defined the _$GameQ_ as the gameq class, and then proceeded to add the server to the array list. So far all is good.

But then you defined _$GameQ_ again (this overrides the first definition, and consequently the list of servers added), and since there is no server added after this new definition of _$GameQ_ it does not preform a query request, because it effectively has nothing to query, hence the empty Array() response.

----
Your final code should look like this:
```
<?php
require_once('Autoloader.php');

$GameQ = new GameQ\GameQ(); // or $GameQ = \GameQ\GameQ::factory();
$GameQ->addServer([
    'type'    => 'rust',
    'host'    => '136.243.95.38:28015',
]);
 
$GameQ->setOption('timeout', 5); // seconds
$GameQ->addFilter('normalize');
$GameQ->addFilter('secondstohuman');
$GameQ->addFilter('stripcolors');

$results = $GameQ->process();
print_r($results);
?>
```

Regards,
Wilson
