### ISSUE TITLE
Atlas shows players online for 16hours

### ISSUE THREAD

**Issue by Angrygargamel** [Austinb/GameQ#509]
hey there
im not sure if this is a problem caused by atlas itself...
but the viewer shows me players on my atlas server for 16hours and more
looks like it doesnt delete them from the list when they disconnect and still show them as online when they already have disconnected
sites like
https://atlasserverlist.com/
https://www.battlemetrics.com/servers/atlas
list them correctly...

i wonder if others have the same problem or if im the only one yet

**Comment by Austinb** [comment]
Since this protocol is based off of Source I would say it is an issue that hasnt been fixed by the game developer.  Unless other servers using Source are showing the same issue there isn't much I can do.

Other sites may be having the same issue they are just assuming after 86400 seconds they are probably not connected.  Also the id's and names are empty so if that is the case you can probably just ignore any entries that match id ==0 and isEmpty(name).  Please open the issue if you find more information.

**Comment by Angrygargamel** [comment]
alright...
i have tried a rcon tool for atlas now... which shows the players correctly.. including names
so it seems the rcon request with password is more accurate than the one without
is there a way you can check this out so far?

regards
