### ISSUE TITLE
Minecraft Bungeecord-Server

### ISSUE THREAD

**Issue by MDMAN** [Austinb/GameQ#510]
Hi.
I have been using the API for a long time and have run several Minecraft servers. All servers are read out and the status is displayed. But all bungeecord - servers have no information. Can not the API read Bungeecord - servers?

**Comment by uilson** [comment]
Hi. 
Probably bungeecord servers need a different packets to query them since they are a modification to the normal game to allow to send players seamlessly from one server to another server. 

Only by inspecting the server responses or getting the packets info from the mod developers, will it be possible to maybe adjust the current protocol to accommodate the mod, or create a new protocol for querying the bungeecord servers.

**Comment by Martin-Rider** [comment]
Hi,

If you enable the query in config.yml and use query port 25577, BungeeCord will work.
