### ISSUE TITLE
New Game Request: Raceroom

### ISSUE THREAD

**Issue by Martin-Rider** [Austinb/GameQ#527]
I wish that the game Raceroom will be implemented.

**Comment by Austinb** [comment]
If you can provide documentation on the query protocol or another querying library that supports this game please provide that information. Without that information this game will not be added.

**Comment by Martin-Rider** [comment]
https://m.mediawiki.org/wiki/API:Main_page

**Comment by uilson** [comment]
> https://m.mediawiki.org/wiki/API:Main_page

Are you joking with us?
Please dont waste the time we, especially Austinb, take from our lifes to bring this to the community for free.

**Comment by Martin-Rider** [comment]
Oh, sorry, I see I sent the wrong link. I found something here that might help you, but I'm not sure. 

https://github.com/sector3studios/r3e-api

**Comment by Austinb** [comment]
Unfortunately this appears to have to run on the same machine as the game server since it looks at the actual executable for the game server.  Is there a way to query the information provided in this example https://github.com/sector3studios/r3e-spectator-overlay/blob/master/r3e-data.json via a network call?  Or if there is another query library that supports querying these types of servers we can use that as a roadmap.
