### ISSUE TITLE
PHP 7.4: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by Martin-Rider** [Austinb/GameQ#533]
Error Message: Array and string offset access syntax with curly braces is deprecated

Stack Trace: \\GameQ\\Autoloader.php","line":58,"function"

**Comment by uilson** [comment]
The problem is not on the gameQ autoloader, but somewhere in your code. 
I also run 7.4 and dont have that problem.

Please update the post with more details, like the code where you call the gameQ library.

The problem is, most likely, that you are using "$var{something}", Instead of "$var[something]" somewhere on your code.
The use of { } to get individual characters inside a string has been deprecated and should be used [ ] in its place.

**Comment by Austinb** [comment]
If you find a specific line of code please open this issue back up.  You may also have better luck using the composer installer version.  I have not checked the adhoc autoloader recently.
