### ISSUE TITLE
GMOD Server Stats unavailable or wrong info.

### ISSUE THREAD

**Issue by devu4** [Austinb/GameQ#537]
I was querying this server 208.103.169.33:27017 but it return either offline or the player count is totally wrong. This is intermittent. Usually notice it when over 50 players.

Any idea why? Server is showing fine on steam and gtracker
https://www.gametracker.com/server_info/208.103.169.33:27017/ 

Getting this error when I enable debug option:

GameQ\Exception\Protocol: Unable to read length=4 from buffer. Bad protocol format or return? 
in GameQ/Buffer.php:133 Stack trace: #0 
GameQ/Buffer.php(416): GameQ\Buffer->read(4) #1 
GameQ/Protocols/Source.php(485): GameQ\Buffer->readInt32Signed() #2 [internal function]: GameQ\Protocols\Source->processPlayers(Object(GameQ\Buffer)) #3 
GameQ/Protocols/Source.php(213): call_user_func_array(Array, Array) #4 
GameQ/GameQ.php(585): GameQ\Protocols\Source->processResponse() #5 
GameQ/GameQ.php(357): GameQ\GameQ->doParseResponse(Object(GameQ\Server)) #6 
GameQ\GameQ->process() #7 {main} 

Seems processing players is completely failing.

**Comment by uilson** [comment]
**INFO** for possible fix.
 
I have not looked further into this, but from what I could see in a quick network packet snifing, using Wireshark, it looks like your server is returning extra packets, before the default response with the server info.

This then come back as an error because GameQ does not see the packet response it was expecting, it tries to processe the response, but it can't parse it.

Its possible a mod present on your server, as I tested 2 other servers in the same IP range, presents on gametracker, and they also failed due to the returned extra packets.

And 1 from other IP that parsed correctly, because no extra packets.

**Comment by Austinb** [comment]
Has something changed with split packets maybe for that mod?  I will see if I can get an output and do some debugging on the response.

**Comment by Austinb** [comment]
I queried a couple of servers including 208.103.169.16:27015 which returns correctly. 

Stepping through the responses there is an issue in the player and rules responses causing the parser to choke and error out.  I am not sure but it appears something is manipulating the response coming from the server as it doesn't match the expected format.  There are other servers showing the same response.  I am not sure the cause at this point.

**Comment by TheSerion** [comment]
Maybe I could put in my two cents?

Hi, I've been following this development for a couple of years now and
never actually had anything that might be helpful or relevant to say until
now.

All these servers use the same hosting company 'GMCHosting' which claims to
have a super super duper custom anti DDoS system. One of the 'features'
their network fakes the 'ping' the client sees in the server browser; these
servers regardless of distance will always appear to be between 9 and 13
ping for the client irrespective of location.
I've only seen this with Garry's mod servers so far - and so far seems to
be unique to this GSP [ https://gmchosting.com/ ].

There is some f--kery going on for sure - my first thought was, because of
the pings they had a cloudflare like implementation a service like CFlare,
or having queries redirect to something that writes its own responses?

I recently came across this post [
https://forum.facepunch.com/gmodgd/iyre/Best-DDoS-protected-host/1/ ] which
was quite eye opening. The owner of this hosting company mentions he uses
something along the line of this?
https://github.com/blastehh/SourceQueryCacheMono . Maybe his implementation
modifies the cashed queries in such a way as well which might explain
incorrect player counts OP mentioned?
I have no doubt however someones capitalizing on what is essentially an
exploit at the cost of the players; then marketing it as a completely
acceptable practice.

I hope this might help shed some light on what might be happening here, I'm
willing to bet the issues are related to this.

Big thank you to you both for all the hard work you do on GameQ,

**Comment by Austinb** [comment]
This issue maybe related to #534.  Please pull down code from v3 and run your code again.  Please let me know if it fixes your issues.

**Comment by Austinb** [comment]
Please open this issue again if you are still having the issue when using the latest v3 build (not release).

**Comment by MrFallen** [comment]
Garry's mod wrong information

`{"teams": [], "gq_mod": "", "gq_name": "Garry's Mod", "gq_type": "gmod", "players": [], "gq_online": "", "gq_address": "46.174.51.162", "gq_mapname": "", "gq_gametype": "", "gq_hostname": "", "gq_joinlink": "steam://connect/46.174.51.162:27015/", "gq_password": "", "gq_protocol": "source", "gq_dedicated": "", "gq_transport": "udp", "gq_maxplayers": "", "gq_numplayers": "", "gq_port_query": "27015", "gq_port_client": "27015"}`
