### ISSUE TITLE
PHP 7.4: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by Martin-Rider** [Austinb/GameQ#543]
After some research I found the buffer where in line 154 is the error with PHP 7.4. After correction the error is gone.

line 154 was changed 
from
$string = $this->data{strlen($this->data) - 1};
to
$string = $this->data(strlen($this->data) - 1);

see: https://github.com/Austinb/GameQ/issues/533

**Comment by uilson** [comment]
This was fixed quite some time ago. 
If you where using the latest files, you would not have had this problem.

Always make sure you are using the latest files from the repository before open issues with the code, that way there would not be need to open "false" error issues.


Also use [ ] instead of ( ) to be compliente with php guide lines, like I told you in the last issue you opened. You could have reopened that issue, you have that option if it is closed, no need to create a new one.

**Comment by Austinb** [comment]
Was fixed in 39d022a via #514.  If you are not using the latest version it is possible you will have bugs.  See also https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Buffer.php#L154

Before opening any more "bug" reports make sure you are using the latest released version.  Right now that version is 3.0.15.
