### ISSUE TITLE
CS 1.6 - Unable to read length=4 from buffer. Bad protocol format or return

### ISSUE THREAD

**Issue by dudekm** [Austinb/GameQ#550]
Hi!

I have a problem with getting informations about CS 1.6. IPs to check:

54.36.186.16:27035 - Unable to read length=4 from buffer. Bad protocol format or return?
188.165.19.26:27215 - Unable to read length=4 from buffer. Bad protocol format or return?

**Comment by Austinb** [comment]
For 54.36.186.16:27035 the issue appears to be that server specifically. The challenge response is not the correct length (it is 1 character short).  When you spit out the raw return from the challenge response it shows up as `<FF><FF><FF><FF>E^@^@` where the 5th character is `E` when it should be an `A` (0x41) as per https://developer.valvesoftware.com/wiki/Server_queries#A2S_SERVERQUERY_GETCHALLENGE.  

Polling a random CS 1.6 server from Gametracker the challenger response is something like `<FF><FF><FF><FF>A<D1><C5><E5>` where the 5th character is `A`.  

I would check your install and any mods you have added or other changes you made to the server and see what is causing the issue.  I am unable to provide any more help since the server is not replying in the correct format. 

Tried the server at 188.165.19.26:27215 but it shows up as offline.
