### ISSUE TITLE
Minecraft online servers are marked as offline - $packets = 13 characters

### ISSUE THREAD

**Issue by dudekm** [Austinb/GameQ#551]
Hi.
I'm receiving wrong info about Minecraft server status (online/offline). During debugging I've recognized that:

GameQ.php file, line 476:
$packets = $server->protocol()->getPacket('!' . Protocol::PACKET_CHALLENGE); 

OK, $packets = 15 characters
Not working, packets = 13 characters.

**Example?**
Analitycy.net:25565 // it's fine, server is online
gc2.pl:25565 // doesn't work. server is online but it's marked as offline

**EDIT**
I found another reason. If you are trying check server, and server has SRV record, server will be marked as offline - ALWAYS!

**Comment by Austinb** [comment]
Is querying enabled for the server at 193.70.81.18:25565 and on that port?  Minecraft uses Gamespy3 which is used by many other games. Since the server at 145.239.89.163:25565 works correctly it is mostly likely not the Gamespy3 class. This then points me to something specific to the server hosting the game, the network in front of the server or the game server itself (i.e. port not enabled or incorrect port).  When doing a quick test the server at 193.70.81.18:2556 it does not even return the challenge packet response which makes me think the traffic is being dropped or the query port is incorrect/disabled. 

The SRV record shouldn't matter as GameQ just uses PHP to resolve the domain to an ip address.  It is possible PHP or the host may be messing up and returning the incorrect IP address when it resolves if the domain has SRV records.  Please try using the IP address only.
