### ISSUE TITLE
Wrong query port for 7Days to Die

### ISSUE THREAD

**Issue by tossat** [Austinb/GameQ#564]
Wrong query port is used to query a game server running '7 Days to Die' (sevendaystodie).

Currently 'port_diff' should be zero (=0):
```php
class Sevendaystodie extends Source
{
   ...
    /**
     * query_port = client_port
     *
     * @type int
     */
    protected $port_diff = 0;
}
```
---
GameServer-Version: 19.03

**Comment by Austinb** [comment]
Was something changed in this protocol?  It is a steam based game so it is usually either the same port or the client port + 1. Please provide a server to test.

**Comment by tossat** [comment]
So in this case it is the same port (=client port).

**Comment by bumbummen99** [comment]
https://7dtd.illy.bz/wiki/Ports

~~Looks like there is some confusion. Base port = query port but Game port = base port + 2. If you then use your normal IP+(Game)Port -2 would be correct, otherwise +0 is correct. Since in GameQ we pass the client port and not the base port -2 will be patched in, otherwise we would break the join url.~~

Alright looks like i got confused. Steam actually expects the base port as i have verified locally so +0 is indeed correct. Sorry.
