### ISSUE TITLE
Add Stationeers Protocol

### ISSUE THREAD

**Issue by Acer90** [Austinb/GameQ#659]
Hello Devs,

Can you please include stationeers as a protocol. Data from the server can be obtained via the portal server:
Output is already as JSON.

Link to Portal
http://[40.82.200.175:8081/list](http://40.82.200.175:8081/list)

Acer

**Comment by Erani0** [comment]
hello i tried your tag but i can take a look again is this the only port from the server? Kind regards

**Comment by Erani0** [comment]
So currently I see no way to query the server unless you install a restfulapi on the server yourself.
The data of the portal server helps you because this is a listing of the servers and not the own server.

I searched the web for api documentation but couldn't find anything. there seems to be only an api integration through a bepinex installation
https://github.com/RoboPhred/stationeers-webapi

Since I can not create my own server because the pterodactyl egg does not work. I can also not create a server for the restful API.

**Comment by Austinb** [comment]
Since you are able to get to the server's information via a simple HTTP request (click on this link [http://40.82.200.175:8081/list](http://40.82.200.175:8081/list)) there should be no issue adding this protocol.  See https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Tshock.php for one example using the Http protocol class.  There are a couple other protocols that use straight Http to make query requests.

**Comment by Erani0** [comment]
That this works I know but this is apparently a kind of server list and not a direct query from the server

**Comment by Erani0** [comment]
Currently you query the list to find the servers but if someone doesn't show his server in the list he will be shown as offline so it's really more advisable to wait for an official support or to enable this via the linked api.
