### ISSUE TITLE
A2S protocol problem

### ISSUE THREAD

**Issue by OfficerFields** [Austinb/GameQ#663]
Hi there,

I have a problem with all servers that use the A2S protocol.
I'm using the latest GameQ version and I can only query my A2S servers when I set the environment variable "STEAM_GAMESERVER_A2S_INFO_STRICT_LEGACY_PROTOCOL" to 1 (Windows Server 2019). After that, the servers show as online, but I can't get the list of players (the number of players works, actually).

Sorry if I missed something to set up. Any idea what might cause the problem?

Thanks!

**Comment by Erani0** [comment]
not all servers send a list of players

**Comment by OfficerFields** [comment]
I‘m aware of that, but this issue happens in my case for Insurgency, Team Fortress 2 and 7 Days To Die. Those servers used to send a list of players via GameQ. I know that there was an update to Valve‘s Source serverquery which was implemented in GameQ, but it still does not work for me.

**Comment by Ruslan-700** [comment]
try this for source protocol

    protected $packets = [
        self::PACKET_CHALLENGE => "\xFF\xFF\xFF\xFF\x56\x00\x00\x00\x00",
        self::PACKET_DETAILS   => "\xFF\xFF\xFF\xFFTSource Engine Query\x00%s",
        self::PACKET_PLAYERS   => "\xFF\xFF\xFF\xFF\x55%s",
        self::PACKET_RULES     => "\xFF\xFF\xFF\xFF\x56%s",
        'details_old'          => "\xFF\xFF\xFF\xFFTSource Engine Query\x00",
    ];

**Comment by OfficerFields** [comment]
Thank you for the suggestion @Ruslan-700. I tried it, unfortunately there is still no player reporting.

**Comment by Ruslan-700** [comment]
Unfortunately, this breaks games with a new protocol, such as rust. Need to find another solution

**Comment by Erani0** [comment]
7 days to Die has never transferred the player list should be tested

Ruslan-700 ***@***.***> schrieb am Sa., 1. Okt. 2022, 14:40:

**Comment by Ruslan-700** [comment]
https://developer.valvesoftware.com/wiki/Server_queries#Response_Format

Servers may respond with the data immediately. However, since this reply is larger than the request, it makes the server vulnerable to a reflection amplification attack. Instead, the server may reply with a challenge to the client using S2C_CHALLENGE ('A' or 0x41). In that case, the client should repeat the request by appending the challenge number. This change was introduced in December 2020 to address the reflection attack vulnerability, and all clients are encouraged to support the new protocol.

**Comment by Ruslan-700** [comment]
We need to make the first request without a challenge, if we receive a challenge in response, we make a second request with a challenge

**Comment by Ruslan-700** [comment]
https://pastebin.com/MCeXCGWR
this is temporary solution, you can't call it beautiful or optimal

**Comment by Erani0** [comment]
7Days to die not work!

"players":[{"id":0,"name":"","score":0,"time":2004.292724609375,"gq_name":"","gq_score":0,"gq_time":2004.292724609375},{"id":0,"name":"","score":0,"time":159.89271545410156,"gq_name":"","gq_score":0,"gq_time":159.89271545410156}]

**Comment by Krymonota** [comment]
Not stale

**Comment by Austinb** [comment]
Did some digging and looked at 7 days specifically using this server list - https://7daystodie-servers.com/.  Many servers would not query using the new or old info calls.  But those that did work all of them required the updated protocol request using the [changes here](https://github.com/Austinb/GameQ/commit/b3b7c17cbf92ea7f5a25060728380994e3b407b1). Also, 7 days has never returned the player names.  None of the tests created for the game have player names in the responses.  Many games do not provide player name in the A2S_Players response for various reasons.  Looking at the raw response the player name is not in there to be shown from any 7 days server I was able to get a response from. 

As for TF2: every server queried using the latest version from v3 branch worked and showed player names in the responses. As for Insurgency: every server queried using the latest version from v3 branch worked and showed player names in the responses. In all cases these are servers listed publicly from BattleMetrics. 

As to making multiple queries sending the INFO call without the challenge and then sending it with if needed is a waste of time and processing.  If the server is old it will probably just drop everything after the packet request type.  If not then an override can be built into the server classes that require the old query way if needed. 

Please check against the last available version in v3 branch (not releases as those tend to be behind). If you have an issue please open a new issue since this one is cluttered with different issues that are not related (i.e. no information vs no player information).
