### ISSUE TITLE
doom 3 - blank numplayers field

### ISSUE THREAD

**Issue by godknowsu** [Austinb/GameQ#70]
Hey,

I found a bug at the game doom 3 with numplayers field. Shows blank.

http://i48.tinypic.com/160bq4j.png

**Comment by Blackskyliner** [comment]
Indeed.
Can be fixed by changing the following in the doom3.php (at least I think so - not so familiar with the protocol thing and can't test atm) (also no git powered comuter so no patch just this snippet - will do some tests and push a patch soon, if austin is not faster than me fixing this issue) 

We could also get it through the getInfo maybe but I dont know how this command output looks like. My solution should work nonetheless.

```
        /**
     * Parse the players.  Set as its own method so it can be overloaded.
     *
     * @param GameQ_Buffer $buf
     * @param GameQ_Result $result
     */
    protected function parsePlayers(GameQ_Buffer &$buf, GameQ_Result &$result)
    {
                $numplayers = 0;
        while (($id = $buf->readInt8()) != 32)
        {
            $result->addPlayer('id',   $id);
            $result->addPlayer('ping', $buf->readInt16());
            $result->addPlayer('rate', $buf->readInt32());
            $result->addPlayer('name', $buf->readString());
                        $numplayers++;
        }
                $result->add('num_players', $numplayers);
        return true;
    }

```

Oh yea and tell me if it worked :)

**Comment by geniv** [comment]
hi, yes, it worked, forked GameQ, in fork is fixed

**Comment by godknowsu** [comment]
It works! :+1: Thank you so much!

**Comment by Austinb** [comment]
Using the normailse (sp) filter actually filled out the gq_numplayers but you are correct in that it was not available as just numplayers.  

geniv next time you make a fix feel free to issue a pull request.
