### ISSUE TITLE
The problem of the Rust game

### ISSUE THREAD

**Issue by es1538** [Austinb/GameQ#703]
### Discussed in https://github.com/Austinb/GameQ/discussions/702

<div type='discussions-op-text'>

<sup>Originally posted by **es1538** May 15, 2023</sup>
I have tried various ports and does not output server data to any, there are no problems with other games. I tried just the port and the Query port
For example, the server 45.63.67.84:28016 works fine, but for example the server 185.189.255.135:35100 does not work, I tried different ones, some work, and some do not
![screenshot](https://github.com/Austinb/GameQ/assets/133704292/fb379001-a863-4ed4-a712-b24cdbac62c2)
</div>

**Comment by Austinb** [comment]
Since you stated that the server at 45.63.67.84:28016 works then there is no issue with the protocol.  Just because it does not work on other servers does not mean it is a GameQ issue.  There could be many reasons why you are unable to query a server, blocked port, ip restricted access to port, query port is custom (different than standard), etc...

**Comment by es1538** [comment]
IP: 185.189.255.135:35100 (Query port: 35110) here is my server data, but even specifying 'options' => ['query_port' => '35110'] nothing happens. There is simply no connection, and there are many such servers, a single 45.63.67.84:28016 connected.
