### ISSUE TITLE
fwrite() error

### ISSUE THREAD

**Issue by DaLaw** [Austinb/GameQ#80]
Hi Austinb,

Thank you for this platform, it's incredibly useful.

I've made use of your platform on a test server at home and got everything running, however, when I moved it over to a hosted space I received the following errors:

Notice: fwrite() [function.fwrite]: send of 7 bytes failed with errno=1 Operation not permitted in /home/rroom/public_html/GameQ.php on line 573

Notice: fwrite() [function.fwrite]: send of 25 bytes failed with errno=1 Operation not permitted in /home/rroom/public_html/GameQ.php on line 640

I've tried figuring out what the challenge could be in terms of PHP settings, however, everything required seems to be enabled in terms of writing and socket access (I might be wrong?)

My PHPInfo is available from here:
http://www.readyroom.co.za/phpinfo.php

Can you tell me what I'm missing?

Thank you.

**Comment by zeagon** [comment]
Had the same issue on a clients site. Most likely hosting has blocked most outgoing ports beside http port 80 in their firewall. Might you be on godaddy, hostgator, 1and1 and the likes? pretty sure most of these biggies dont allow this on their shared hosting plans

**Comment by Austinb** [comment]
Because it works locally and not remotely I think zeagon is probably correct.  A lot of hosting services block a lot of outgoing ports and connections at the firewall level to prevent people from doing bad things or just generating a lot of traffic in general. 

My guess is something is preventing the script from sending data out.  Its possible the ports arent even being created.

**Comment by Gasjki** [comment]
You can add @ to avoid errors on line 64, Query/Native.php . I've got this error too, and that's how I hide :)
