### ISSUE TITLE
DayZ Query Question

### ISSUE THREAD

**Issue by Ruok2bu** [Austinb/GameQ#85]
I learned the following:

"When you query a dayz server after a server restart, it sits in idle mode until someone joins at which time the map and mission loads up and it can be queried normally again."

Is there any way around this?  Servers that are restarted have been showing up as offline until a player connects.

**Comment by Austinb** [comment]
Interesting behavior.  I can not really test for this since I do not have a dayz server or the game for that matter. If you can provide some sort of temp server that is unlisted I can check against.  Is this an issue with the game? Have you seen any other posts about this anywhere else?  If so please link. Thanks

**Comment by Ruok2bu** [comment]
Here's 2 servers that ive been having trouble querying:

74.121.190.162:2302
192.210.150.226:2305

**Comment by Austinb** [comment]
So I just tested this and I found the following:
- 74.121.190.162:2302 is up and returns player info.
- 192.210.150.226:2305 shows as down and there is no response from the query.  There is no packet returned.  Even the challenge response packet is empty.  So it will show up as offline.  Is there a setting on the server to allow you to kickstart it once the server first starts?  Something like change the map as soon as the server starts up the first time?

This appears to be an issue with the actual server, unless that server is currently down.  Let me know.
