### ISSUE TITLE
Support: Increasing query performance

### ISSUE THREAD

**Issue by oskari** [Austinb/GameQ#91]
Hey, I'm querying 4 different Arma2 OA servers (which all run a submod to a DayZ-mod) and was wondering if there would be a way to increase query performance somehow? I currently only need the player names that are online and I guess GameQ creates some overhead with it's features when only looking for specified info. Or should I ditch whole library and write my own for this sole purpose?

**Comment by Austinb** [comment]
The issue is specific to GameSpy 3.  Once you send the challenge packet you have to send any other request packets for information (GameQ does a query all information in a single packet) on the same socket as the challenge packet was sent.  This makes GameSpy 3 slower compared to Source (which allows multiple packets on multiple sockets) because you have to send then read, then send and it blocks other server requests until the current one finishes.  I am still looking for a clean solution for GameSpy 3 specifically to try to make it faster. 

Changing the packet to just player details probably would not make the query speed up any faster. However a simple script may be better suited for your specific needs.  If you have any ideas or thoughts please feel free to share.  The GameSpy 3 speed issue is one that I really want to solve but don't have the time currently to devote to solving it.
