### ISSUE TITLE
Only first ~340 servers appear online

### ISSUE THREAD

**Issue by KostyaEsmukov** [Austinb/GameQ#98]
How to reproduce: take near 500-1000 servers from gametracker(I've tested left4dead2 servers) and add them to GameQ, then run request. Servers starting from ~340 are always offline. Challenge requests are sent by GameQ, but servers responses are ignored (though they fit in timeout). Tried setting insane timeouts (stream_timeout => 1000000, timeout => 10) - nothing changed.
I know that GameQ was developed for average users, but take a look into that, may be it has easy fix.

**Comment by Austinb** [comment]
Yea I have gotten notes about this from various people.  The odd thing is it is always about the same number of servers then it just stops returning results.  I am not sure if it is a PHP limitation like memory_limit or if it is something in the code doing something wrong.  My money is on the latter but I have not had any real time to debug it.

**Comment by matbcvo** [comment]
Having same problem,
Link: http://s.staatus.eu/?page=servers
30 servers, only half is online, but really they're all online. All servers are cached every 5 minutes. It uses "add servers to array then send query", etc.
php.ini
memory_limit = 128M

Any idea how fix that?

**Comment by KostyaEsmukov** [comment]
As a workaround you can query servers by portions. For example, no more than 10 servers at the same time.

**Comment by skylord123** [comment]
I use gearman for tracking vast amounts of servers. I just set the limit to 300 servers per worker. I was able to track 50,000~55,000 servers of various server types in under 2 minutes and 30 seconds. Used a total peak bandwidth of 9mbps. It would have gone faster but there is some server type that takes a while to respond, can't remember what it is called.. oh well.

Anyways, I recommend using a similar load balancing system for your needs. You can even have multiple workers working side by side processing the load at the same time (in my instance I had 10 workers going doing 300 servers each, then grabbing the next stack).

**Comment by ghost** [comment]
Nothing to do with the PHP limit, have mine at 1GB, if that helps you in any way. Is it by any chance related to the timeout, maybe its not applying the timeout per server but rather for the entire array?

**Comment by BombermaG** [comment]
This problem exists because $this->timeout doesn't work in this loop.
I marked some strings of code as "FIXME" tag, read them.

``` php

        // This is when it should stop
        $time_stop = microtime(TRUE) + $this->timeout;

        // Let's loop until we break something.
        while ($loop_active && microtime(TRUE) < $time_stop)
        {
            // Now lets listen for some streams, but do not cross the streams!
            $streams = stream_select($read, $write, $except, 0, $this->stream_timeout);

            // We had error or no streams left, kill the loop
            // @FIXME: If $this->stream_timeout is small, we are exit from loop,
            //          because streams <= 0
            if($streams === FALSE || ($streams <= 0))
            {
                $loop_active = FALSE;
                break;
            }

            // Loop the sockets that received data back
            foreach($read AS $socket)
            {
                // See if we have a response
                if(($response = stream_socket_recvfrom($socket, 8192)) === FALSE)
                {
                    continue; // No response yet so lets continue.
                }

                // Check to see if the response is empty, if so we are done
                // @todo: Verify that this does not affect other protocols, added for Minequery
                // Initial testing showed this change did not affect any of the other protocols
                // @FIXME: If someone minecraft server return empty response,
                //          we are exit from loop and other responses are ignored
                if (strlen($response) == 0)
                {
                    // End the while loop
                    $loop_active = FALSE;
                    break;
                }

                // Add the response we got back
                $responses[(int) $socket][] = $response;
            }

            // Because stream_select modifies read we need to reset it each
            // time to the original array of sockets
            $read = $sockets;
        }

        // Free up some memory
        unset($streams, $read, $write, $except, $sockets, $time_stop, $response);

        return $responses;
```

This is my test. Check 10 servers with stream_timeout = 1 and timeout = 3. All servers are online. 
Result:
02:51:27.44367 Open socket with port: 42190
02:51:27.44441 Open socket with port: 45259
02:51:27.44512 Open socket with port: 55121
02:51:27.44583 Open socket with port: 60514
02:51:27.44664 Close socket with port: 42190
02:51:27.44670 Close socket with port: 45259
02:51:27.44673 Close socket with port: 55121
02:51:27.44677 Close socket with port: 60514
02:51:27.44683 Open socket with port: 45887
02:51:27.44748 Open socket with port: 35298
02:51:27.44818 Open socket with port: 33635
02:51:27.44892 Open socket with port: 49518
02:51:27.44962 Open socket with port: 32775
02:51:27.45032 Open socket with port: 36434
02:51:27.45104 Open socket with port: 57380
02:51:27.45174 Open socket with port: 56358
02:51:27.45254 Close socket with port: 45887
02:51:27.45257 Close socket with port: 35298
02:51:27.45259 Close socket with port: 33635
02:51:27.45260 Close socket with port: 49518
02:51:27.45262 Close socket with port: 32775
02:51:27.45264 Close socket with port: 36434
02:51:27.45266 Close socket with port: 57380
02:51:27.45268 Close socket with port: 56358
02:51:27.45273 Open socket with port: 38845
02:51:27.45371 Open socket with port: 45389
02:51:27.45450 Close socket with port: 45389
Servers online: 1

In tcpdump we are see this ICMP response:
02:51:27.449534 IP 46.110.49.6 > 76.174.59.29: ICMP 46.110.49.6 udp port 55121 unreachable, length 45
02:51:27.451662 IP 46.110.49.6 > 76.174.59.27: ICMP 46.110.49.6 udp port 60514 unreachable, length 45
02:51:27.454898 IP 46.110.49.6 > 76.174.59.46: ICMP 46.110.49.6 udp port 45389 unreachable, length 556
02:51:27.460229 IP 46.110.49.6 > 76.174.59.48: ICMP 46.110.49.6 udp port 33635 unreachable, length 87
02:51:27.466579 IP 46.110.49.6 > 76.174.59.29: ICMP 46.110.49.6 udp port 32775 unreachable, length 146
02:51:27.469254 IP 46.110.49.6 > 76.174.59.48: ICMP 46.110.49.6 udp port 36434 unreachable, length 118
Because we closed socket before received an answer and timeout doesn't expired.

To fix it, we must rewrite logic of exit from while loop. Example, drop socket from $sockets array if we are receive all packets needed by required query protocol, then exit from loop if $sockets is empty or timeout is expired.

Sorry for my English.

**Comment by Austinb** [comment]
The stream_timeout option is only for the amount of time to wait for responses before moving on through the loop.  This value is in usec (micro) and the lower the number the more cpu intensive the script.  If you set this really small (like 1) I can see where it could cause issues. 

I am closing this issue as v3 should hopefully fix long standing issues with larger lists of servers. Please test v3 and provide feedback as I am no longer messing with the internals of v2.

**Comment by BombermaG** [comment]
I know what is stream_timeout and how it works. I say about $this->timeout and it's not work as must be.
See your code with my comments and you are maybe understand what i mean.
Example.
timeout - Default: 3 (seconds). Amount of time a server has to respond to a query before assuming the server is offline.
stream_timeout = 200000
In current realization of _while_ loop if we have 2 game servers with 300 ms ping, it always be offline, because stream_select return 0 streams after 200000 microseconds wait and we are exit from loop in this place:

``` php
            if($streams === FALSE || ($streams <= 0))
            {
                $loop_active = FALSE;
                break;
            }
```

And we don't wait 3 seconds of $this->timeout. Do you understand what I mean? $this->timeout doesn't work in current realization.
And this code is copied to v3.

**Comment by BombermaG** [comment]
I tested v3. Same problem. This is not surprising, because used same code.

**Comment by Austinb** [comment]
The $timeout property is there to prevent servers that don't respond in a "timely" manner from holding up the script from finishing because they never respond. It is basically a fail-safe but if we can we should return as soon as all of the servers are done responding which is what the $streams <= 0 is for. Removing the $streams <= 0 part causes the loop to run until $timeout is reached in the while() loop which would be expected.  With that code as it is exists now I have yet to run into any issues while testing smaller clusters of servers.  It is possible the section needs to be rebuilt for larger lists or auto-tweak $timeout when the list is larger.

Sockets are not my strong suit so I am very interested in tweaking the script or even rebuilding it if need be but I need more information to test with so I can see what you are seeing. If you have some thoughts on reworking it please provide changes and some servers to test against that dont work with the existing but do with your changes.  Reopening for more thought and input from others perhaps.

**Comment by BombermaG** [comment]
"If we can we should return as soon as all of the servers are done responding" - best way do it is check response, if received needed packet by protocol then delete (int) $socket from $sockets array. If not received, wait more time until $this->timeout is not expired.
If $sockets array is empty or $this->timeout is expired - exit from loop.
We don't have another ways to check it.

For test you can get any servers from gametracker.com. I took some servers from China, ping from me to them is more than 300 ms. It more than default stream_timeout.

**Comment by Austinb** [comment]
That idea is interesting except that it changes a lot of the current layout of the library.   The socket side has no idea the protocol side even exists as it just sends and receives data.  To implement something like you are suggesting would require processing on the fly of the packets which may be out of order or split apart.  It is not impossible but it requires a lot of changes. As far as I can see there is no way to test if a UDP stream is done (i,e, EOF).  Again I am not that great with sockets in general.  If anyone has any other ideas or thoughts please chime in.

The default stream_timeout was set based on some testing I did with servers in the US and EU and it was a happy medium between speed and wasted time waiting for servers to respond.  It will not suit everyone which is why it is a configurable option.
